# Palette derived from Modus (GPL v3); see colors/LICENSE

default_variant = "modus_operandi"

# Optional per-host overrides. Example:
# [hosts.my-hostname]
# default_variant = "modus_vivendi"
[hosts]

[variants.modus_operandi]
flavor = "light"
foreground = "#000000"
background = "#ffffff"
cursor = "#000000"
selection_background = "#dfa0f0"
selection_foreground = "#000000"
ansi = [
  "#ffffff",
  "#a60000",
  "#006800",
  "#6f5500",
  "#0031a9",
  "#721045",
  "#005e8b",
  "#000000",
  "#e0e0e0",
  "#d00000",
  "#008900",
  "#808000",
  "#0000ff",
  "#dd22dd",
  "#008899",
  "#595959",
]

[variants.modus_operandi.extended]
none = "NONE"
bg_main = "#ffffff"
bg_dim = "#f2f2f2"
bg_alt = "#f0f0f0"
fg_main = "#000000"
fg_dim = "#595959"
fg_alt = "#193668"
border = "#9f9f9f"
border_highlight = "#3b3b3b"
red = "#a60000"
red_warmer = "#972500"
red_cooler = "#a0132f"
red_faint = "#7f0000"
green = "#006800"
green_warmer = "#316500"
green_cooler = "#00663f"
green_faint = "#2a5045"
yellow = "#6f5500"
yellow_warmer = "#884900"
yellow_cooler = "#7a4f2f"
yellow_faint = "#624416"
blue = "#0031a9"
blue_warmer = "#3548cf"
blue_cooler = "#0000b0"
blue_faint = "#003497"
magenta = "#721045"
magenta_warmer = "#8f0075"
magenta_cooler = "#531ab6"
magenta_faint = "#7c318f"
cyan = "#005e8b"
cyan_warmer = "#3f578f"
cyan_cooler = "#005f5f"
cyan_faint = "#005077"
rust = "#8a290f"
gold = "#80601f"
olive = "#56692d"
slate = "#2f3f83"
indigo = "#4a3a8a"
maroon = "#731c52"
pink = "#7b435c"
red_intense = "#d00000"
green_intense = "#008900"
yellow_intense = "#808000"
blue_intense = "#0000ff"
magenta_intense = "#dd22dd"
cyan_intense = "#008899"
bg_red_intense = "#ff8f88"
bg_green_intense = "#8adf80"
bg_yellow_intense = "#f3d000"
bg_blue_intense = "#bfc9ff"
bg_magenta_intense = "#dfa0f0"
bg_cyan_intense = "#a4d5f9"
bg_red_subtle = "#ffcfbf"
bg_green_subtle = "#b3fabf"
bg_yellow_subtle = "#fff576"
bg_blue_subtle = "#ccdfff"
bg_magenta_subtle = "#ffddff"
bg_cyan_subtle = "#bfefff"
bg_red_nuanced = "#fff1f0"
bg_green_nuanced = "#ecf7ed"
bg_yellow_nuanced = "#fff3da"
bg_blue_nuanced = "#f3f3ff"
bg_magenta_nuanced = "#fdf0ff"
bg_cyan_nuanced = "#ebf6fa"
bg_completion = "#c0deff"
bg_hl_line = "#dae5ec"
bg_paren_match = "#5fcfff"
bg_paren_expression = "#efd3f5"
bg_char_0 = "#7feaff"
bg_char_1 = "#ffaaff"
bg_char_2 = "#dff000"
bg_active = "#e0e0e0"
fg_active = "#0a0a0a"
bg_inactive = "#e9e9e9"
fg_inactive = "#404148"
bg_status_line_active = "#c8c8c8"
fg_status_line_active = "#0a0a0a"
bg_status_line_inactive = "#e6e6e6"
fg_status_line_inactive = "#585858"
bg_tab_bar = "#dfdfdf"
bg_tab_current = "#ffffff"
bg_tab_other = "#c2c2c2"
fg_tab_other = "#333333"
bg_tab_alternate = "#c2c2e8"
bg_added = "#c1f2d1"
bg_added_faint = "#d8f8e1"
bg_added_refine = "#aee5be"
bg_added_fringe = "#6cc06c"
fg_added = "#005000"
fg_added_intense = "#006700"
bg_changed = "#ffdfa9"
bg_changed_faint = "#ffefbf"
bg_changed_refine = "#fac090"
bg_changed_fringe = "#d7c20a"
fg_changed = "#553d00"
fg_changed_intense = "#655000"
bg_removed = "#ffd8d5"
bg_removed_faint = "#ffe9e9"
bg_removed_refine = "#f3b5af"
bg_removed_fringe = "#d84a4f"
fg_removed = "#8f1313"
fg_removed_intense = "#aa2222"
bg_diff_context = "#f3f3f3"
tinted_bg_main = "#fbf7f0"
tinted_bg_dim = "#efe9dd"
tinted_border = "#9f9690"
tinted_border_highlight = "#5c3f3d"
tinted_bg_active = "#c9b9b0"
tinted_bg_inactive = "#dfd5cf"
tinted_red_faint = "#7f0000"
tinted_bg_red_nuanced = "#ffe8f0"
tinted_bg_green_nuanced = "#e0f5e0"
tinted_bg_yellow_nuanced = "#f9ead0"
tinted_bg_blue_nuanced = "#ebebff"
tinted_bg_magenta_nuanced = "#f6e7ff"
tinted_bg_cyan_nuanced = "#e1f3fc"
tinted_bg_completion = "#f0c1cf"
tinted_bg_hl_line = "#f1d5d0"
tinted_bg_paren_match = "#7fdfcf"
tinted_bg_status_line_active = "#cab9b2"
tinted_bg_status_line_inactive = "#dfd9cf"
tinted_bg_tab_bar = "#e0d4ce"
tinted_bg_tab_current = "#fbf7f0"
tinted_bg_tab_other = "#c8b8b2"
tinted_bg_tab_alternate = "#c8b8ca"
tinted_bg_added = "#c3ebc1"
tinted_bg_added_faint = "#dcf8d1"
tinted_bg_added_refine = "#acd6a5"
tinted_bg_added_fringe = "#6cc06c"
tinted_bg_changed_fringe = "#c0b200"
tinted_bg_removed = "#f4d0cf"
tinted_bg_removed_faint = "#ffe9e5"
tinted_bg_removed_refine = "#f3b5a7"
tinted_bg_removed_fringe = "#d84a4f"
tinted_bg_diff_context = "#efe9df"

[variants.modus_vivendi]
flavor = "dark"
foreground = "#ffffff"
background = "#000000"
cursor = "#ffffff"
selection_background = "#7030af"
selection_foreground = "#ffffff"
ansi = [
  "#000000",
  "#ff5f59",
  "#44bc44",
  "#d0bc00",
  "#2fafff",
  "#feacd0",
  "#00d3d0",
  "#ffffff",
  "#303030",
  "#ff5f5f",
  "#44df44",
  "#efef00",
  "#338fff",
  "#ff66ff",
  "#00eff0",
  "#989898",
]

[variants.modus_vivendi.extended]
none = "NONE"
bg_main = "#000000"
bg_dim = "#1e1e1e"
bg_alt = "#0f0f0f"
fg_main = "#ffffff"
fg_dim = "#989898"
fg_alt = "#c6daff"
border = "#646464"
border_highlight = "#C4C4C4"
red = "#ff5f59"
red_warmer = "#ff6b55"
red_cooler = "#ff7f9f"
red_faint = "#ff9580"
green = "#44bc44"
green_warmer = "#70b900"
green_cooler = "#00c06f"
green_faint = "#88ca9f"
yellow = "#d0bc00"
yellow_warmer = "#fec43f"
yellow_cooler = "#dfaf7a"
yellow_faint = "#d2b580"
blue = "#2fafff"
blue_warmer = "#79a8ff"
blue_cooler = "#00bcff"
blue_faint = "#82b0ec"
magenta = "#feacd0"
magenta_warmer = "#f78fe7"
magenta_cooler = "#b6a0ff"
magenta_faint = "#caa6df"
cyan = "#00d3d0"
cyan_warmer = "#4ae2f0"
cyan_cooler = "#6ae4b9"
cyan_faint = "#9ac8e0"
rust = "#db7b5f"
gold = "#c0965b"
olive = "#9cbd6f"
slate = "#76afbf"
indigo = "#9099d9"
maroon = "#cf7fa7"
pink = "#d09dc0"
red_intense = "#ff5f5f"
green_intense = "#44df44"
yellow_intense = "#efef00"
blue_intense = "#338fff"
magenta_intense = "#ff66ff"
cyan_intense = "#00eff0"
bg_red_intense = "#9d1f1f"
bg_green_intense = "#2f822f"
bg_yellow_intense = "#7a6100"
bg_blue_intense = "#1640b0"
bg_magenta_intense = "#7030af"
bg_cyan_intense = "#2266ae"
bg_red_subtle = "#620f2a"
bg_green_subtle = "#00422a"
bg_yellow_subtle = "#4a4000"
bg_blue_subtle = "#242679"
bg_magenta_subtle = "#552f5f"
bg_cyan_subtle = "#004065"
bg_red_nuanced = "#2c0614"
bg_green_nuanced = "#001904"
bg_yellow_nuanced = "#222000"
bg_blue_nuanced = "#0f0e39"
bg_magenta_nuanced = "#230631"
bg_cyan_nuanced = "#041529"
bg_completion = "#2f447f"
bg_hl_line = "#2f3849"
bg_paren_match = "#2f7f9f"
bg_paren_expression = "#453040"
bg_char_0 = "#0050af"
bg_char_1 = "#7f1f7f"
bg_char_2 = "#625a00"
bg_active = "#303030"
fg_active = "#f4f4f4"
bg_inactive = "#282828"
fg_inactive = "#bfc0c4"
bg_status_line_active = "#404040"
fg_status_line_active = "#f0f0f0"
bg_status_line_inactive = "#2d2d2d"
fg_status_line_inactive = "#969696"
bg_tab_bar = "#313131"
bg_tab_current = "#000000"
bg_tab_other = "#545454"
fg_tab_other = "#f7f7f7"
bg_tab_alternate = "#545490"
bg_added = "#00381f"
bg_added_faint = "#002910"
bg_added_refine = "#034f2f"
bg_added_fringe = "#237f3f"
fg_added = "#a0e0a0"
fg_added_intense = "#80e080"
bg_changed = "#363300"
bg_changed_faint = "#2a1f00"
bg_changed_refine = "#4a4a00"
bg_changed_fringe = "#8a7a00"
fg_changed = "#efef80"
fg_changed_intense = "#c0b05f"
bg_removed = "#4f1119"
bg_removed_faint = "#380a0f"
bg_removed_refine = "#781a1f"
bg_removed_fringe = "#b81a1f"
fg_removed = "#ffbfbf"
fg_removed_intense = "#ff9095"
bg_diff_context = "#1a1a1a"
tinted_bg_main = "#0d0e1c"
tinted_bg_dim = "#1d2235"
tinted_border = "#61647a"
tinted_border_highlight = "#b290b0"
tinted_bg_active = "#4a4f69"
tinted_bg_inactive = "#2b3045"
tinted_red_faint = "#ff9f80"
tinted_bg_red_nuanced = "#350f14"
tinted_bg_green_nuanced = "#002718"
tinted_bg_yellow_nuanced = "#2c1f00"
tinted_bg_blue_nuanced = "#131c4d"
tinted_bg_magenta_nuanced = "#2f133f"
tinted_bg_cyan_nuanced = "#04253f"
tinted_bg_completion = "#483d8a"
tinted_bg_hl_line = "#303a6f"
tinted_bg_paren_match = "#2f7f9f"
tinted_bg_status_line_active = "#393F51"
tinted_bg_status_line_inactive = "#292d48"
tinted_bg_tab_bar = "#2c3045"
tinted_bg_tab_current = "#0d0e1c"
tinted_bg_tab_other = "#4a4f6a"
tinted_bg_tab_alternate = "#4a4f94"
tinted_bg_added = "#003a2f"
tinted_bg_added_faint = "#002922"
tinted_bg_added_refine = "#035542"
tinted_bg_added_fringe = "#23884f"
tinted_bg_changed_fringe = "#8f7a30"
tinted_bg_removed = "#4f1127"
tinted_bg_removed_faint = "#380a19"
tinted_bg_removed_refine = "#781a3a"
tinted_bg_removed_fringe = "#b81a26"
tinted_bg_diff_context = "#1a1f30"
