model = "gpt-5.2-codex"
"hide_gpt-5.1-codex-max_migration_prompt" = true
model_reasoning_effort = "medium"

web_search_request = true

notify = ["sh", "~/.codex/hooks/notify_bridge"]
personality = "pragmatic"

[projects."/Users/phajas/dotfiles"]
trust_level = "trusted"
