# Palette for Catppuccin

[families.catppuccin]
name = 'Catppuccin'
license = 'MIT'
light_variant = 'catppuccin_latte'
dark_variant = 'catppuccin_frappe'

[variants.catppuccin_latte]
family = 'catppuccin'
flavor = 'light'
foreground = '#4c4f69'
background = '#eff1f5'
cursor = '#4c4f69'
selection_background = '#8839ef'
selection_foreground = '#eff1f5'
ansi = [
  '#dce0e8',
  '#d20f39',
  '#40a02b',
  '#df8e1d',
  '#1e66f5',
  '#8839ef',
  '#179299',
  '#4c4f69',
  '#9ca0b0',
  '#e64553',
  '#40a02b',
  '#df8e1d',
  '#04a5e5',
  '#ea76cb',
  '#209fb5',
  '#5c5f77',
]

[variants.catppuccin_latte.extended]
none = 'NONE'
bg_main = '#eff1f5'
bg_dim = '#e6e9ef'
bg_alt = '#dce0e8'
fg_main = '#4c4f69'
fg_dim = '#6c6f85'
fg_alt = '#5c5f77'
border = '#9ca0b0'
border_highlight = '#7c7f93'
red = '#d20f39'
red_warmer = '#fe640b'
red_cooler = '#e64553'
red_faint = '#ea76cb'
green = '#40a02b'
green_warmer = '#40a02b'
green_cooler = '#179299'
green_faint = '#179299'
yellow = '#df8e1d'
yellow_warmer = '#fe640b'
yellow_cooler = '#df8e1d'
yellow_faint = '#df8e1d'
blue = '#1e66f5'
blue_warmer = '#7287fd'
blue_cooler = '#209fb5'
blue_faint = '#04a5e5'
magenta = '#8839ef'
magenta_warmer = '#ea76cb'
magenta_cooler = '#8839ef'
magenta_faint = '#ea76cb'
cyan = '#179299'
cyan_warmer = '#04a5e5'
cyan_cooler = '#209fb5'
cyan_faint = '#04a5e5'
rust = '#fe640b'
gold = '#df8e1d'
olive = '#40a02b'
slate = '#1e66f5'
indigo = '#8839ef'
maroon = '#e64553'
pink = '#ea76cb'
red_intense = '#d20f39'
green_intense = '#40a02b'
yellow_intense = '#df8e1d'
blue_intense = '#1e66f5'
magenta_intense = '#8839ef'
cyan_intense = '#179299'
bg_red_intense = '#f4b8e4'
bg_green_intense = '#a6d189'
bg_yellow_intense = '#eed49f'
bg_blue_intense = '#8aadf4'
bg_magenta_intense = '#f4b8e4'
bg_cyan_intense = '#91d7e3'
bg_red_subtle = '#ea76cb'
bg_green_subtle = '#ccd0da'
bg_yellow_subtle = '#ccd0da'
bg_blue_subtle = '#ccd0da'
bg_magenta_subtle = '#f4b8e4'
bg_cyan_subtle = '#ccd0da'
bg_red_nuanced = '#eff1f5'
bg_green_nuanced = '#eff1f5'
bg_yellow_nuanced = '#eff1f5'
bg_blue_nuanced = '#eff1f5'
bg_magenta_nuanced = '#eff1f5'
bg_cyan_nuanced = '#eff1f5'
bg_active = '#ccd0da'
fg_active = '#4c4f69'
bg_inactive = '#bcc0cc'
fg_inactive = '#6c6f85'
bg_active_argument = '#ccd0da'
bg_active_value = '#ccd0da'
bg_completion = '#ccd0da'
bg_hl_line = '#e6e9ef'
bg_paren_match = '#04a5e5'
bg_paren_expression = '#8839ef'
bg_char_0 = '#04a5e5'
bg_char_1 = '#ea76cb'
bg_char_2 = '#df8e1d'
bg_region = '#8839ef'
bg_status_line_active = '#dce0e8'
fg_status_line_active = '#4c4f69'
bg_status_line_inactive = '#e6e9ef'
fg_status_line_inactive = '#6c6f85'
bg_tab_bar = '#dce0e8'
bg_tab_current = '#eff1f5'
bg_tab_other = '#e6e9ef'
fg_tab_other = '#6c6f85'
bg_tab_alternate = '#8839ef'
bg_added = '#acb0be'
bg_added_faint = '#eff1f5'
bg_added_refine = '#40a02b'
bg_added_fringe = '#40a02b'
fg_added = '#40a02b'
fg_added_intense = '#40a02b'
bg_changed = '#acb0be'
bg_changed_faint = '#eff1f5'
bg_changed_refine = '#df8e1d'
bg_changed_fringe = '#df8e1d'
fg_changed = '#df8e1d'
fg_changed_intense = '#df8e1d'
bg_removed = '#acb0be'
bg_removed_faint = '#eff1f5'
bg_removed_refine = '#d20f39'
bg_removed_fringe = '#d20f39'
fg_removed = '#d20f39'
fg_removed_intense = '#d20f39'
bg_diff_context = '#eff1f5'
tinted_bg_main = '#e6e9ef'
tinted_bg_dim = '#dce0e8'
tinted_border = '#9ca0b0'
tinted_border_highlight = '#7c7f93'
tinted_bg_active = '#bcc0cc'
tinted_bg_inactive = '#ccd0da'
tinted_red_faint = '#ea76cb'
tinted_bg_red_nuanced = '#e6e9ef'
tinted_bg_green_nuanced = '#e6e9ef'
tinted_bg_yellow_nuanced = '#e6e9ef'
tinted_bg_blue_nuanced = '#e6e9ef'
tinted_bg_magenta_nuanced = '#e6e9ef'
tinted_bg_cyan_nuanced = '#e6e9ef'
tinted_bg_completion = '#bcc0cc'
tinted_bg_hl_line = '#dce0e8'
tinted_bg_paren_match = '#04a5e5'
tinted_bg_status_line_active = '#dce0e8'
tinted_bg_status_line_inactive = '#e6e9ef'
tinted_bg_tab_bar = '#dce0e8'
tinted_bg_tab_current = '#e6e9ef'
tinted_bg_tab_other = '#bcc0cc'
tinted_bg_tab_alternate = '#8839ef'
tinted_bg_added = '#acb0be'
tinted_bg_added_faint = '#e6e9ef'
tinted_bg_added_refine = '#40a02b'
tinted_bg_added_fringe = '#40a02b'
tinted_bg_changed_fringe = '#df8e1d'
tinted_bg_removed = '#acb0be'
tinted_bg_removed_faint = '#e6e9ef'
tinted_bg_removed_refine = '#d20f39'
tinted_bg_removed_fringe = '#d20f39'
tinted_bg_diff_context = '#e6e9ef'
visual = '#8839ef'
link = '#1e66f5'
link_visited = '#8839ef'
link_symbolic = '#179299'
string = '#40a02b'
comment = '#9ca0b0'
constant = '#fe640b'
identifier = '#1e66f5'
keyword = '#8839ef'
type = '#df8e1d'
fnname = '#1e66f5'
variable = '#d20f39'
rainbow_0 = '#d20f39'
rainbow_1 = '#40a02b'
rainbow_2 = '#df8e1d'
rainbow_3 = '#1e66f5'
rainbow_4 = '#8839ef'
rainbow_5 = '#179299'
rainbow_6 = '#ea76cb'
rainbow_7 = '#fe640b'
prose_todo = '#d20f39'
prose_done = '#40a02b'
prose_tag = '#8839ef'
prose_table = '#1e66f5'
err = '#d20f39'
warning = '#df8e1d'
info = '#1e66f5'

[variants.catppuccin_frappe]
family = 'catppuccin'
flavor = 'dark'
foreground = '#c6d0f5'
background = '#303446'
cursor = '#c6d0f5'
selection_background = '#ca9ee6'
selection_foreground = '#303446'
ansi = [
  '#232634',
  '#e78284',
  '#a6d189',
  '#e5c890',
  '#8caaee',
  '#ca9ee6',
  '#81c8be',
  '#c6d0f5',
  '#737994',
  '#ea999c',
  '#a6d189',
  '#e5c890',
  '#99d1db',
  '#f4b8e4',
  '#85c1dc',
  '#b5bfe2',
]

[variants.catppuccin_frappe.extended]
none = 'NONE'
bg_main = '#303446'
bg_dim = '#292c3c'
bg_alt = '#232634'
fg_main = '#c6d0f5'
fg_dim = '#a5adce'
fg_alt = '#b5bfe2'
border = '#737994'
border_highlight = '#949cbb'
red = '#e78284'
red_warmer = '#ef9f76'
red_cooler = '#ea999c'
red_faint = '#f4b8e4'
green = '#a6d189'
green_warmer = '#a6d189'
green_cooler = '#81c8be'
green_faint = '#81c8be'
yellow = '#e5c890'
yellow_warmer = '#ef9f76'
yellow_cooler = '#e5c890'
yellow_faint = '#e5c890'
blue = '#8caaee'
blue_warmer = '#babbf1'
blue_cooler = '#85c1dc'
blue_faint = '#99d1db'
magenta = '#ca9ee6'
magenta_warmer = '#f4b8e4'
magenta_cooler = '#ca9ee6'
magenta_faint = '#f4b8e4'
cyan = '#81c8be'
cyan_warmer = '#99d1db'
cyan_cooler = '#85c1dc'
cyan_faint = '#99d1db'
rust = '#ef9f76'
gold = '#e5c890'
olive = '#a6d189'
slate = '#8caaee'
indigo = '#ca9ee6'
maroon = '#ea999c'
pink = '#f4b8e4'
red_intense = '#e78284'
green_intense = '#a6d189'
yellow_intense = '#e5c890'
blue_intense = '#8caaee'
magenta_intense = '#ca9ee6'
cyan_intense = '#81c8be'
bg_red_intense = '#ea999c'
bg_green_intense = '#a6d189'
bg_yellow_intense = '#e5c890'
bg_blue_intense = '#8caaee'
bg_magenta_intense = '#f4b8e4'
bg_cyan_intense = '#99d1db'
bg_red_subtle = '#51576d'
bg_green_subtle = '#51576d'
bg_yellow_subtle = '#51576d'
bg_blue_subtle = '#51576d'
bg_magenta_subtle = '#51576d'
bg_cyan_subtle = '#51576d'
bg_red_nuanced = '#303446'
bg_green_nuanced = '#303446'
bg_yellow_nuanced = '#303446'
bg_blue_nuanced = '#303446'
bg_magenta_nuanced = '#303446'
bg_cyan_nuanced = '#303446'
bg_active = '#414559'
fg_active = '#c6d0f5'
bg_inactive = '#51576d'
fg_inactive = '#a5adce'
bg_active_argument = '#414559'
bg_active_value = '#414559'
bg_completion = '#414559'
bg_hl_line = '#292c3c'
bg_paren_match = '#99d1db'
bg_paren_expression = '#ca9ee6'
bg_char_0 = '#99d1db'
bg_char_1 = '#f4b8e4'
bg_char_2 = '#e5c890'
bg_region = '#ca9ee6'
bg_status_line_active = '#232634'
fg_status_line_active = '#c6d0f5'
bg_status_line_inactive = '#292c3c'
fg_status_line_inactive = '#a5adce'
bg_tab_bar = '#232634'
bg_tab_current = '#303446'
bg_tab_other = '#292c3c'
fg_tab_other = '#a5adce'
bg_tab_alternate = '#ca9ee6'
bg_added = '#626880'
bg_added_faint = '#303446'
bg_added_refine = '#a6d189'
bg_added_fringe = '#a6d189'
fg_added = '#a6d189'
fg_added_intense = '#a6d189'
bg_changed = '#626880'
bg_changed_faint = '#303446'
bg_changed_refine = '#e5c890'
bg_changed_fringe = '#e5c890'
fg_changed = '#e5c890'
fg_changed_intense = '#e5c890'
bg_removed = '#626880'
bg_removed_faint = '#303446'
bg_removed_refine = '#e78284'
bg_removed_fringe = '#e78284'
fg_removed = '#e78284'
fg_removed_intense = '#e78284'
bg_diff_context = '#303446'
tinted_bg_main = '#292c3c'
tinted_bg_dim = '#232634'
tinted_border = '#737994'
tinted_border_highlight = '#949cbb'
tinted_bg_active = '#51576d'
tinted_bg_inactive = '#414559'
tinted_red_faint = '#f4b8e4'
tinted_bg_red_nuanced = '#292c3c'
tinted_bg_green_nuanced = '#292c3c'
tinted_bg_yellow_nuanced = '#292c3c'
tinted_bg_blue_nuanced = '#292c3c'
tinted_bg_magenta_nuanced = '#292c3c'
tinted_bg_cyan_nuanced = '#292c3c'
tinted_bg_completion = '#51576d'
tinted_bg_hl_line = '#232634'
tinted_bg_paren_match = '#99d1db'
tinted_bg_status_line_active = '#232634'
tinted_bg_status_line_inactive = '#292c3c'
tinted_bg_tab_bar = '#232634'
tinted_bg_tab_current = '#292c3c'
tinted_bg_tab_other = '#51576d'
tinted_bg_tab_alternate = '#ca9ee6'
tinted_bg_added = '#626880'
tinted_bg_added_faint = '#292c3c'
tinted_bg_added_refine = '#a6d189'
tinted_bg_added_fringe = '#a6d189'
tinted_bg_changed_fringe = '#e5c890'
tinted_bg_removed = '#626880'
tinted_bg_removed_faint = '#292c3c'
tinted_bg_removed_refine = '#e78284'
tinted_bg_removed_fringe = '#e78284'
tinted_bg_diff_context = '#292c3c'
visual = '#ca9ee6'
link = '#8caaee'
link_visited = '#ca9ee6'
link_symbolic = '#81c8be'
string = '#a6d189'
comment = '#737994'
constant = '#ef9f76'
identifier = '#8caaee'
keyword = '#ca9ee6'
type = '#e5c890'
fnname = '#8caaee'
variable = '#e78284'
rainbow_0 = '#e78284'
rainbow_1 = '#a6d189'
rainbow_2 = '#e5c890'
rainbow_3 = '#8caaee'
rainbow_4 = '#ca9ee6'
rainbow_5 = '#81c8be'
rainbow_6 = '#f4b8e4'
rainbow_7 = '#ef9f76'
prose_todo = '#e78284'
prose_done = '#a6d189'
prose_tag = '#ca9ee6'
prose_table = '#8caaee'
err = '#e78284'
warning = '#e5c890'
info = '#8caaee'
