# Palette for Ef Duo

[families.ef_duo]
name = 'Ef Duo'
license = 'GPL v3'
light_variant = 'ef_duo_light'
dark_variant = 'ef_duo_dark'

[variants.ef_duo_light]
family = 'ef_duo'
flavor = 'light'
foreground = '#222222'
background = '#fff8f0'
cursor = '#1144ff'
selection_background = '#caeafa'
selection_foreground = '#222222'
ansi = [
  '#fff8f0',
  '#cc3333',
  '#217a3c',
  '#8a5d00',
  '#375cd8',
  '#ba35af',
  '#1f6fbf',
  '#222222',
  '#f6ece8',
  '#dd1100',
  '#4a7d00',
  '#9f4a00',
  '#4250ef',
  '#cf25aa',
  '#3f70a0',
  '#63728f',
]

[variants.ef_duo_light.extended]
none = 'NONE'
bg_main = '#fff8f0'
bg_dim = '#f6ece8'
bg_alt = '#e7e0da'
fg_main = '#222222'
fg_dim = '#63728f'
fg_alt = '#856f4a'
border = '#baafba'
border_highlight = '#856f4a'
red = '#cc3333'
red_warmer = '#dd1100'
red_cooler = '#c04440'
red_faint = '#a2403f'
green = '#217a3c'
green_warmer = '#4a7d00'
green_cooler = '#008058'
green_faint = '#61756c'
yellow = '#8a5d00'
yellow_warmer = '#9f4a00'
yellow_cooler = '#8f5a3a'
yellow_faint = '#765640'
blue = '#375cd8'
blue_warmer = '#4250ef'
blue_cooler = '#065fff'
blue_faint = '#6060d0'
magenta = '#ba35af'
magenta_warmer = '#cf25aa'
magenta_cooler = '#6052cf'
magenta_faint = '#af569f'
cyan = '#1f6fbf'
cyan_warmer = '#3f70a0'
cyan_cooler = '#1f77bb'
cyan_faint = '#406f90'
rust = '#dd1100'
gold = '#8a5d00'
olive = '#4a7d00'
slate = '#6060d0'
indigo = '#6052cf'
maroon = '#c04440'
pink = '#cf25aa'
red_intense = '#cc3333'
green_intense = '#217a3c'
yellow_intense = '#8a5d00'
blue_intense = '#375cd8'
magenta_intense = '#ba35af'
cyan_intense = '#1f6fbf'
bg_red_intense = '#ff8f88'
bg_green_intense = '#8adf80'
bg_yellow_intense = '#fac200'
bg_blue_intense = '#cbcfff'
bg_magenta_intense = '#df8fff'
bg_cyan_intense = '#88c8ff'
bg_red_subtle = '#ffcfbf'
bg_green_subtle = '#aff7c5'
bg_yellow_subtle = '#f9f376'
bg_blue_subtle = '#cfdff9'
bg_magenta_subtle = '#f9ddf0'
bg_cyan_subtle = '#bfeaf0'
bg_red_nuanced = '#ffcfbf'
bg_green_nuanced = '#aff7c5'
bg_yellow_nuanced = '#f9f376'
bg_blue_nuanced = '#cfdff9'
bg_magenta_nuanced = '#f9ddf0'
bg_cyan_nuanced = '#bfeaf0'
bg_completion = '#fadacf'
bg_hl_line = '#f9e8c0'
bg_paren_match = '#afbfef'
bg_paren_expression = '#b4cfff'
bg_char_0 = '#cfdff9'
bg_char_1 = '#f9ddf0'
bg_char_2 = '#f9f376'
bg_active = '#c7c0ba'
fg_active = '#222222'
bg_inactive = '#f9f2ef'
fg_inactive = '#63728f'
bg_status_line_active = '#f8cf8f'
fg_status_line_active = '#111133'
bg_status_line_inactive = '#f6ece8'
fg_status_line_inactive = '#63728f'
bg_tab_bar = '#e7e0da'
bg_tab_current = '#fff8f0'
bg_tab_other = '#c7c0ba'
fg_tab_other = '#63728f'
bg_tab_alternate = '#aaeccf'
bg_added = '#ccefcf'
bg_added_faint = '#e0f3e0'
bg_added_refine = '#bae0c0'
bg_added_fringe = '#bae0c0'
fg_added = '#005000'
fg_added_intense = '#005000'
bg_changed = '#ffe5b9'
bg_changed_faint = '#ffefc5'
bg_changed_refine = '#ffd09f'
bg_changed_fringe = '#ffd09f'
fg_changed = '#553d00'
fg_changed_intense = '#553d00'
bg_removed = '#ffd4d8'
bg_removed_faint = '#ffe3e3'
bg_removed_refine = '#ffc0ca'
bg_removed_fringe = '#ffc0ca'
fg_removed = '#8f1313'
fg_removed_intense = '#8f1313'
bg_diff_context = '#f6ece8'
visual = '#caeafa'
link = '#1f6fbf'
link_visited = '#008058'
link_symbolic = '#1f6fbf'
string = '#9f4a00'
comment = '#a2403f'
constant = '#375cd8'
identifier = '#a2403f'
keyword = '#4250ef'
type = '#065fff'
fnname = '#1f6fbf'
variable = '#6052cf'
rainbow_0 = '#375cd8'
rainbow_1 = '#9f4a00'
rainbow_2 = '#4250ef'
rainbow_3 = '#8f5a3a'
rainbow_4 = '#6052cf'
rainbow_5 = '#4a7d00'
rainbow_6 = '#3f70a0'
rainbow_7 = '#8a5d00'
prose_todo = '#cc3333'
prose_done = '#217a3c'
prose_tag = '#765640'
prose_table = '#856f4a'
err = '#cc3333'
warning = '#8a5d00'
info = '#217a3c'
hint = '#406f90'
ok = '#008058'

[variants.ef_duo_dark]
family = 'ef_duo'
flavor = 'dark'
foreground = '#d0d0d0'
background = '#070019'
cursor = '#ef6f11'
selection_background = '#042a50'
selection_foreground = '#d0d0d0'
ansi = [
  '#070019',
  '#ef656a',
  '#1fa526',
  '#c48702',
  '#379cf6',
  '#d369af',
  '#5faaef',
  '#d0d0d0',
  '#1d1a26',
  '#f47360',
  '#50a22f',
  '#d0730f',
  '#6f80ff',
  '#e580ea',
  '#7fafff',
  '#857f8f',
]

[variants.ef_duo_dark.extended]
none = 'NONE'
bg_main = '#070019'
bg_dim = '#1d1a26'
bg_alt = '#2a2739'
fg_main = '#d0d0d0'
fg_dim = '#857f8f'
fg_alt = '#89afef'
border = '#545f6f'
border_highlight = '#89afef'
red = '#ef656a'
red_warmer = '#f47360'
red_cooler = '#ef798f'
red_faint = '#d08f72'
green = '#1fa526'
green_warmer = '#50a22f'
green_cooler = '#00b982'
green_faint = '#61a06c'
yellow = '#c48702'
yellow_warmer = '#d0730f'
yellow_cooler = '#df805f'
yellow_faint = '#9f8f6a'
blue = '#379cf6'
blue_warmer = '#6f80ff'
blue_cooler = '#029fff'
blue_faint = '#8a9fdf'
magenta = '#d369af'
magenta_warmer = '#e580ea'
magenta_cooler = '#af85ff'
magenta_faint = '#c57faf'
cyan = '#5faaef'
cyan_warmer = '#7fafff'
cyan_cooler = '#0dafdf'
cyan_faint = '#8aa0df'
rust = '#f47360'
gold = '#c48702'
olive = '#50a22f'
slate = '#8a9fdf'
indigo = '#af85ff'
maroon = '#ef798f'
pink = '#e580ea'
red_intense = '#ef656a'
green_intense = '#1fa526'
yellow_intense = '#c48702'
blue_intense = '#379cf6'
magenta_intense = '#d369af'
cyan_intense = '#5faaef'
bg_red_intense = '#cd2f30'
bg_green_intense = '#407720'
bg_yellow_intense = '#8f5040'
bg_blue_intense = '#4648d0'
bg_magenta_intense = '#b04fcf'
bg_cyan_intense = '#2270be'
bg_red_subtle = '#72002a'
bg_green_subtle = '#00422a'
bg_yellow_subtle = '#603000'
bg_blue_subtle = '#242679'
bg_magenta_subtle = '#501f72'
bg_cyan_subtle = '#004065'
bg_red_nuanced = '#72002a'
bg_green_nuanced = '#00422a'
bg_yellow_nuanced = '#603000'
bg_blue_nuanced = '#242679'
bg_magenta_nuanced = '#501f72'
bg_cyan_nuanced = '#004065'
bg_completion = '#2f1a5f'
bg_hl_line = '#301a4f'
bg_paren_match = '#2f608e'
bg_paren_expression = '#664f4a'
bg_char_0 = '#242679'
bg_char_1 = '#501f72'
bg_char_2 = '#603000'
bg_active = '#4a4759'
fg_active = '#d0d0d0'
bg_inactive = '#13101f'
fg_inactive = '#857f8f'
bg_status_line_active = '#352487'
fg_status_line_active = '#dedeff'
bg_status_line_inactive = '#1d1a26'
fg_status_line_inactive = '#857f8f'
bg_tab_bar = '#2a2739'
bg_tab_current = '#070019'
bg_tab_other = '#4a4759'
fg_tab_other = '#857f8f'
bg_tab_alternate = '#264f4a'
bg_added = '#002d1f'
bg_added_faint = '#001f18'
bg_added_refine = '#003b2f'
bg_added_fringe = '#003b2f'
fg_added = '#a0e0a0'
fg_added_intense = '#a0e0a0'
bg_changed = '#323200'
bg_changed_faint = '#2a2000'
bg_changed_refine = '#444000'
bg_changed_fringe = '#444000'
fg_changed = '#efef80'
fg_changed_intense = '#efef80'
bg_removed = '#3d091f'
bg_removed_faint = '#27040f'
bg_removed_refine = '#5b0f26'
bg_removed_fringe = '#5b0f26'
fg_removed = '#ffbfbf'
fg_removed_intense = '#ffbfbf'
bg_diff_context = '#1d1a26'
visual = '#042a50'
link = '#7fafff'
link_visited = '#00b982'
link_symbolic = '#5faaef'
string = '#df805f'
comment = '#d08f72'
constant = '#379cf6'
identifier = '#d08f72'
keyword = '#6f80ff'
type = '#029fff'
fnname = '#0dafdf'
variable = '#af85ff'
rainbow_0 = '#379cf6'
rainbow_1 = '#d0730f'
rainbow_2 = '#6f80ff'
rainbow_3 = '#df805f'
rainbow_4 = '#0dafdf'
rainbow_5 = '#c48702'
rainbow_6 = '#029fff'
rainbow_7 = '#ef798f'
prose_todo = '#ef656a'
prose_done = '#1fa526'
prose_tag = '#9f8f6a'
prose_table = '#89afef'
err = '#ef656a'
warning = '#c48702'
info = '#1fa526'
hint = '#8aa0df'
ok = '#00b982'
