# Palette for Ef Day/Night

[families.ef_daynight]
name = 'Ef Day/Night'
license = 'GPL v3'
light_variant = 'ef_day'
dark_variant = 'ef_night'

[variants.ef_day]
family = 'ef_daynight'
flavor = 'light'
foreground = '#584141'
background = '#fff5ea'
cursor = '#cf1f00'
selection_background = '#f0d2df'
selection_foreground = '#584141'
ansi = [
  '#fff5ea',
  '#ba2d2f',
  '#007a0a',
  '#a45a22',
  '#375cc6',
  '#ca3e54',
  '#3f60af',
  '#584141',
  '#f2e9db',
  '#ce3f00',
  '#5f7200',
  '#b75515',
  '#5f5fdf',
  '#cb2f80',
  '#3f6faf',
  '#63728f',
]

[variants.ef_day.extended]
none = 'NONE'
bg_main = '#fff5ea'
bg_dim = '#f2e9db'
bg_alt = '#e9e0d8'
fg_main = '#584141'
fg_dim = '#63728f'
fg_alt = '#8f5f4a'
border = '#c8bdb6'
border_highlight = '#8f5f4a'
red = '#ba2d2f'
red_warmer = '#ce3f00'
red_cooler = '#cf2f4f'
red_faint = '#b05350'
green = '#007a0a'
green_warmer = '#5f7200'
green_cooler = '#0f7f5f'
green_faint = '#527545'
yellow = '#a45a22'
yellow_warmer = '#b75515'
yellow_cooler = '#aa4f30'
yellow_faint = '#9a625a'
blue = '#375cc6'
blue_warmer = '#5f5fdf'
blue_cooler = '#265fbf'
blue_faint = '#4a659f'
magenta = '#ca3e54'
magenta_warmer = '#cb2f80'
magenta_cooler = '#8448aa'
magenta_faint = '#a04450'
cyan = '#3f60af'
cyan_warmer = '#3f6faf'
cyan_cooler = '#0f7b8f'
cyan_faint = '#4f6f8f'
rust = '#ce3f00'
gold = '#a45a22'
olive = '#5f7200'
slate = '#4a659f'
indigo = '#8448aa'
maroon = '#cf2f4f'
pink = '#cb2f80'
red_intense = '#ba2d2f'
green_intense = '#007a0a'
yellow_intense = '#a45a22'
blue_intense = '#375cc6'
magenta_intense = '#ca3e54'
cyan_intense = '#3f60af'
bg_red_intense = '#ff8f88'
bg_green_intense = '#96df80'
bg_yellow_intense = '#efbf00'
bg_blue_intense = '#cfceff'
bg_magenta_intense = '#df9fff'
bg_cyan_intense = '#88cfd0'
bg_red_subtle = '#ffc6bf'
bg_green_subtle = '#c4f2af'
bg_yellow_subtle = '#f0f07f'
bg_blue_subtle = '#ccdfff'
bg_magenta_subtle = '#fad3ff'
bg_cyan_subtle = '#bfefff'
bg_red_nuanced = '#ffc6bf'
bg_green_nuanced = '#c4f2af'
bg_yellow_nuanced = '#f0f07f'
bg_blue_nuanced = '#ccdfff'
bg_magenta_nuanced = '#fad3ff'
bg_cyan_nuanced = '#bfefff'
bg_completion = '#ffd5d3'
bg_hl_line = '#f9e2b2'
bg_paren_match = '#8fcfdf'
bg_paren_expression = '#b0e0df'
bg_char_0 = '#ccdfff'
bg_char_1 = '#fad3ff'
bg_char_2 = '#f0f07f'
bg_active = '#c9c0b8'
fg_active = '#584141'
bg_inactive = '#f7efe6'
fg_inactive = '#63728f'
bg_status_line_active = '#ffaf72'
fg_status_line_active = '#542f38'
bg_status_line_inactive = '#f2e9db'
fg_status_line_inactive = '#63728f'
bg_tab_bar = '#e9e0d8'
bg_tab_current = '#fff5ea'
bg_tab_other = '#c9c0b8'
fg_tab_other = '#63728f'
bg_tab_alternate = '#febccf'
bg_added = '#ccefcf'
bg_added_faint = '#e0f3e0'
bg_added_refine = '#bae0c0'
bg_added_fringe = '#bae0c0'
fg_added = '#005000'
fg_added_intense = '#005000'
bg_changed = '#ffe5b9'
bg_changed_faint = '#ffefc5'
bg_changed_refine = '#ffd09f'
bg_changed_fringe = '#ffd09f'
fg_changed = '#553d00'
fg_changed_intense = '#553d00'
bg_removed = '#ffd4d8'
bg_removed_faint = '#ffe3e3'
bg_removed_refine = '#ffc0ca'
bg_removed_fringe = '#ffc0ca'
fg_removed = '#8f1313'
fg_removed_intense = '#8f1313'
bg_diff_context = '#f2e9db'
visual = '#f0d2df'
link = '#3f6faf'
link_visited = '#5f7200'
link_symbolic = '#3f60af'
string = '#5f7200'
comment = '#527545'
constant = '#ce3f00'
identifier = '#a04450'
keyword = '#a45a22'
type = '#0f7f5f'
fnname = '#ca3e54'
variable = '#8448aa'
rainbow_0 = '#a45a22'
rainbow_1 = '#ba2d2f'
rainbow_2 = '#5f7200'
rainbow_3 = '#cb2f80'
rainbow_4 = '#3f60af'
rainbow_5 = '#aa4f30'
rainbow_6 = '#8448aa'
rainbow_7 = '#cf2f4f'
prose_todo = '#ce3f00'
prose_done = '#007a0a'
prose_tag = '#9a625a'
prose_table = '#8f5f4a'
err = '#ce3f00'
warning = '#a45a22'
info = '#007a0a'
hint = '#4f6f8f'
ok = '#0f7f5f'

[variants.ef_night]
family = 'ef_daynight'
flavor = 'dark'
foreground = '#afbcbf'
background = '#000e17'
cursor = '#00ccff'
selection_background = '#253146'
selection_foreground = '#afbcbf'
ansi = [
  '#000e17',
  '#ef656a',
  '#1fa526',
  '#c48502',
  '#379cf6',
  '#d570af',
  '#4fb0cf',
  '#afbcbf',
  '#1a202b',
  '#f47360',
  '#50a22f',
  '#e6832f',
  '#6a88ff',
  '#e580ea',
  '#6fafff',
  '#70819f',
]

[variants.ef_night.extended]
none = 'NONE'
bg_main = '#000e17'
bg_dim = '#1a202b'
bg_alt = '#242e39'
fg_main = '#afbcbf'
fg_dim = '#70819f'
fg_alt = '#b0a0a0'
border = '#3a4a66'
border_highlight = '#b0a0a0'
red = '#ef656a'
red_warmer = '#f47360'
red_cooler = '#ef798f'
red_faint = '#d56f72'
green = '#1fa526'
green_warmer = '#50a22f'
green_cooler = '#00a972'
green_faint = '#61a06c'
yellow = '#c48502'
yellow_warmer = '#e6832f'
yellow_cooler = '#df8f6f'
yellow_faint = '#cf9f7f'
blue = '#379cf6'
blue_warmer = '#6a88ff'
blue_cooler = '#029fff'
blue_faint = '#7a94df'
magenta = '#d570af'
magenta_warmer = '#e580ea'
magenta_cooler = '#af8aff'
magenta_faint = '#c59fcf'
cyan = '#4fb0cf'
cyan_warmer = '#6fafff'
cyan_cooler = '#3dc0b0'
cyan_faint = '#92b4df'
rust = '#f47360'
gold = '#c48502'
olive = '#50a22f'
slate = '#7a94df'
indigo = '#af8aff'
maroon = '#ef798f'
pink = '#e580ea'
red_intense = '#ef656a'
green_intense = '#1fa526'
yellow_intense = '#c48502'
blue_intense = '#379cf6'
magenta_intense = '#d570af'
cyan_intense = '#4fb0cf'
bg_red_intense = '#bd1f30'
bg_green_intense = '#107440'
bg_yellow_intense = '#847020'
bg_blue_intense = '#2f5f9f'
bg_magenta_intense = '#804fd5'
bg_cyan_intense = '#0280b9'
bg_red_subtle = '#6a1b2f'
bg_green_subtle = '#0a432f'
bg_yellow_subtle = '#533420'
bg_blue_subtle = '#1f3665'
bg_magenta_subtle = '#502555'
bg_cyan_subtle = '#113b5e'
bg_red_nuanced = '#6a1b2f'
bg_green_nuanced = '#0a432f'
bg_yellow_nuanced = '#533420'
bg_blue_nuanced = '#1f3665'
bg_magenta_nuanced = '#502555'
bg_cyan_nuanced = '#113b5e'
bg_completion = '#00314f'
bg_hl_line = '#002255'
bg_paren_match = '#664950'
bg_paren_expression = '#6f345a'
bg_char_0 = '#1f3665'
bg_char_1 = '#502555'
bg_char_2 = '#533420'
bg_active = '#444e59'
fg_active = '#afbcbf'
bg_inactive = '#11141f'
fg_inactive = '#70819f'
bg_status_line_active = '#003a7f'
fg_status_line_active = '#ceeeff'
bg_status_line_inactive = '#1a202b'
fg_status_line_inactive = '#70819f'
bg_tab_bar = '#242e39'
bg_tab_current = '#000e17'
bg_tab_other = '#444e59'
fg_tab_other = '#70819f'
bg_tab_alternate = '#493737'
bg_added = '#00371f'
bg_added_faint = '#002918'
bg_added_refine = '#004c2f'
bg_added_fringe = '#004c2f'
fg_added = '#a0e0a0'
fg_added_intense = '#a0e0a0'
bg_changed = '#363300'
bg_changed_faint = '#2a1f00'
bg_changed_refine = '#4a4a00'
bg_changed_fringe = '#4a4a00'
fg_changed = '#efef80'
fg_changed_intense = '#efef80'
bg_removed = '#450f1f'
bg_removed_faint = '#2f060f'
bg_removed_refine = '#641426'
bg_removed_fringe = '#641426'
fg_removed = '#ffbfbf'
fg_removed_intense = '#ffbfbf'
bg_diff_context = '#1a202b'
visual = '#253146'
link = '#379cf6'
link_visited = '#af8aff'
link_symbolic = '#4fb0cf'
string = '#029fff'
comment = '#cf9f7f'
constant = '#af8aff'
identifier = '#c59fcf'
keyword = '#6a88ff'
type = '#c59fcf'
fnname = '#3dc0b0'
variable = '#6fafff'
rainbow_0 = '#6fafff'
rainbow_1 = '#af8aff'
rainbow_2 = '#df8f6f'
rainbow_3 = '#6a88ff'
rainbow_4 = '#d570af'
rainbow_5 = '#1fa526'
rainbow_6 = '#c48502'
rainbow_7 = '#4fb0cf'
prose_todo = '#ef656a'
prose_done = '#00a972'
prose_tag = '#b0a0a0'
prose_table = '#b0a0a0'
err = '#ef656a'
warning = '#e6832f'
info = '#00a972'
hint = '#92b4df'
ok = '#00a972'
