# Palette for Ef Deuteranopia

[families.ef_deuteranopia]
name = 'Ef Deuteranopia'
license = 'GPL v3'
light_variant = 'ef_deuteranopia_light'
dark_variant = 'ef_deuteranopia_dark'

[variants.ef_deuteranopia_light]
family = 'ef_deuteranopia'
flavor = 'light'
foreground = '#1a1a2f'
background = '#f5f5ff'
cursor = '#0000bb'
selection_background = '#dadadf'
selection_foreground = '#1a1a2f'
ansi = [
  '#f5f5ff',
  '#d3303a',
  '#217a3c',
  '#805d00',
  '#375cd8',
  '#ba35af',
  '#1f6fbf',
  '#1a1a2f',
  '#e8e8ea',
  '#e00033',
  '#4a7d00',
  '#965000',
  '#4250ef',
  '#cf25aa',
  '#3f6faf',
  '#70627f',
]

[variants.ef_deuteranopia_light.extended]
none = 'NONE'
bg_main = '#f5f5ff'
bg_dim = '#e8e8ea'
bg_alt = '#d3d3e0'
fg_main = '#1a1a2f'
fg_dim = '#70627f'
fg_alt = '#196f70'
border = '#bcbcd0'
border_highlight = '#196f70'
red = '#d3303a'
red_warmer = '#e00033'
red_cooler = '#d50f7f'
red_faint = '#a04852'
green = '#217a3c'
green_warmer = '#4a7d00'
green_cooler = '#008058'
green_faint = '#61756c'
yellow = '#805d00'
yellow_warmer = '#965000'
yellow_cooler = '#765040'
yellow_faint = '#77604a'
blue = '#375cd8'
blue_warmer = '#4250ef'
blue_cooler = '#065fff'
blue_faint = '#6060d0'
magenta = '#ba35af'
magenta_warmer = '#cf25aa'
magenta_cooler = '#6052cf'
magenta_faint = '#9f5080'
cyan = '#1f6fbf'
cyan_warmer = '#3f6faf'
cyan_cooler = '#1477b2'
cyan_faint = '#506fa0'
rust = '#e00033'
gold = '#805d00'
olive = '#4a7d00'
slate = '#6060d0'
indigo = '#6052cf'
maroon = '#d50f7f'
pink = '#cf25aa'
red_intense = '#d3303a'
green_intense = '#217a3c'
yellow_intense = '#805d00'
blue_intense = '#375cd8'
magenta_intense = '#ba35af'
cyan_intense = '#1f6fbf'
bg_red_intense = '#cac200'
bg_green_intense = '#9aaf80'
bg_yellow_intense = '#fac200'
bg_blue_intense = '#cbcfff'
bg_magenta_intense = '#3fbfff'
bg_cyan_intense = '#98e8ff'
bg_red_subtle = '#ead270'
bg_green_subtle = '#bae0a0'
bg_yellow_subtle = '#e6f270'
bg_blue_subtle = '#c0dfff'
bg_magenta_subtle = '#ccc8ff'
bg_cyan_subtle = '#afecf0'
bg_red_nuanced = '#ead270'
bg_green_nuanced = '#bae0a0'
bg_yellow_nuanced = '#e6f270'
bg_blue_nuanced = '#c0dfff'
bg_magenta_nuanced = '#ccc8ff'
bg_cyan_nuanced = '#afecf0'
bg_completion = '#f0dacf'
bg_hl_line = '#f3e0d5'
bg_paren_match = '#8fc0cf'
bg_paren_expression = '#eebb20'
bg_char_0 = '#c0dfff'
bg_char_1 = '#ccc8ff'
bg_char_2 = '#e6f270'
bg_active = '#b3b3c0'
fg_active = '#1a1a2f'
bg_inactive = '#efeff5'
fg_inactive = '#70627f'
bg_status_line_active = '#99c7ff'
fg_status_line_active = '#0a0a1f'
bg_status_line_inactive = '#e8e8ea'
fg_status_line_inactive = '#70627f'
bg_tab_bar = '#d3d3e0'
bg_tab_current = '#f5f5ff'
bg_tab_other = '#b3b3c0'
fg_tab_other = '#70627f'
bg_tab_alternate = '#afafef'
bg_added = '#dbdbff'
bg_added_faint = '#e4e4ff'
bg_added_refine = '#c0c0ef'
bg_added_fringe = '#c0c0ef'
fg_added = '#333399'
fg_added_intense = '#333399'
bg_changed = '#eecfdf'
bg_changed_faint = '#f0dde5'
bg_changed_refine = '#e0b0d0'
bg_changed_fringe = '#e0b0d0'
fg_changed = '#6f1343'
fg_changed_intense = '#6f1343'
bg_removed = '#fff0af'
bg_removed_faint = '#efefcb'
bg_removed_refine = '#f0da88'
bg_removed_fringe = '#f0da88'
fg_removed = '#553d00'
fg_removed_intense = '#553d00'
bg_diff_context = '#e8e8ea'
visual = '#dadadf'
link = '#375cd8'
link_visited = '#765040'
link_symbolic = '#1f6fbf'
string = '#965000'
comment = '#77604a'
constant = '#765040'
identifier = '#506fa0'
keyword = '#4250ef'
type = '#805d00'
fnname = '#065fff'
variable = '#1477b2'
rainbow_0 = '#375cd8'
rainbow_1 = '#805d00'
rainbow_2 = '#4250ef'
rainbow_3 = '#765040'
rainbow_4 = '#065fff'
rainbow_5 = '#965000'
rainbow_6 = '#6060d0'
rainbow_7 = '#77604a'
prose_todo = '#965000'
prose_done = '#065fff'
prose_tag = '#61756c'
prose_table = '#196f70'
err = '#965000'
warning = '#765040'
info = '#065fff'
hint = '#506fa0'
ok = '#008058'

[variants.ef_deuteranopia_dark]
family = 'ef_deuteranopia'
flavor = 'dark'
foreground = '#ddddee'
background = '#000a1f'
cursor = '#ffff00'
selection_background = '#223848'
selection_foreground = '#ddddee'
ansi = [
  '#000a1f',
  '#cf8560',
  '#3faa26',
  '#aa9f32',
  '#3f90f0',
  '#b379bf',
  '#5faaef',
  '#ddddee',
  '#121f34',
  '#e47360',
  '#7aad0f',
  '#cfaf00',
  '#6a9fff',
  '#af80ea',
  '#7fafff',
  '#7f8797',
]

[variants.ef_deuteranopia_dark.extended]
none = 'NONE'
bg_main = '#000a1f'
bg_dim = '#121f34'
bg_alt = '#243145'
fg_main = '#ddddee'
fg_dim = '#7f8797'
fg_alt = '#90afef'
border = '#555a64'
border_highlight = '#90afef'
red = '#cf8560'
red_warmer = '#e47360'
red_cooler = '#cf7a7a'
red_faint = '#b57f82'
green = '#3faa26'
green_warmer = '#7aad0f'
green_cooler = '#3fa672'
green_faint = '#61a06c'
yellow = '#aa9f32'
yellow_warmer = '#cfaf00'
yellow_cooler = '#bfaf7a'
yellow_faint = '#af9a6a'
blue = '#3f90f0'
blue_warmer = '#6a9fff'
blue_cooler = '#009fff'
blue_faint = '#7a94df'
magenta = '#b379bf'
magenta_warmer = '#af80ea'
magenta_cooler = '#9f95ff'
magenta_faint = '#c59fcf'
cyan = '#5faaef'
cyan_warmer = '#7fafff'
cyan_cooler = '#0db0ff'
cyan_faint = '#8aa0df'
rust = '#e47360'
gold = '#aa9f32'
olive = '#7aad0f'
slate = '#7a94df'
indigo = '#9f95ff'
maroon = '#cf7a7a'
pink = '#af80ea'
red_intense = '#cf8560'
green_intense = '#3faa26'
yellow_intense = '#aa9f32'
blue_intense = '#3f90f0'
magenta_intense = '#b379bf'
cyan_intense = '#5faaef'
bg_red_intense = '#8d7f00'
bg_green_intense = '#afcf20'
bg_yellow_intense = '#5f5f00'
bg_blue_intense = '#266fd0'
bg_magenta_intense = '#6f60c0'
bg_cyan_intense = '#007fae'
bg_red_subtle = '#5d3f00'
bg_green_subtle = '#345f20'
bg_yellow_subtle = '#575700'
bg_blue_subtle = '#264f70'
bg_magenta_subtle = '#4a4670'
bg_cyan_subtle = '#265560'
bg_red_nuanced = '#5d3f00'
bg_green_nuanced = '#345f20'
bg_yellow_nuanced = '#575700'
bg_blue_nuanced = '#264f70'
bg_magenta_nuanced = '#4a4670'
bg_cyan_nuanced = '#265560'
bg_completion = '#343420'
bg_hl_line = '#2e2e1b'
bg_paren_match = '#0f4f9a'
bg_paren_expression = '#4f4f00'
bg_char_0 = '#264f70'
bg_char_1 = '#4a4670'
bg_char_2 = '#575700'
bg_active = '#445165'
fg_active = '#ddddee'
bg_inactive = '#0d1429'
fg_inactive = '#7f8797'
bg_status_line_active = '#003f8f'
fg_status_line_active = '#ffffff'
bg_status_line_inactive = '#121f34'
fg_status_line_inactive = '#7f8797'
bg_tab_bar = '#243145'
bg_tab_current = '#000a1f'
bg_tab_other = '#445165'
fg_tab_other = '#7f8797'
bg_tab_alternate = '#00405f'
bg_added = '#00234f'
bg_added_faint = '#00143f'
bg_added_refine = '#03395f'
bg_added_fringe = '#03395f'
fg_added = '#c4d5ff'
fg_added_intense = '#c4d5ff'
bg_changed = '#2f123f'
bg_changed_faint = '#1f022f'
bg_changed_refine = '#3f224f'
bg_changed_fringe = '#3f224f'
fg_changed = '#e3cfff'
fg_changed_intense = '#e3cfff'
bg_removed = '#323200'
bg_removed_faint = '#281a00'
bg_removed_refine = '#484800'
bg_removed_fringe = '#484800'
fg_removed = '#d4d48f'
fg_removed_intense = '#d4d48f'
bg_diff_context = '#121f34'
visual = '#223848'
link = '#3f90f0'
link_visited = '#bfaf7a'
link_symbolic = '#5faaef'
string = '#3f90f0'
comment = '#af9a6a'
constant = '#009fff'
identifier = '#8aa0df'
keyword = '#cfaf00'
type = '#9f95ff'
fnname = '#bfaf7a'
variable = '#0db0ff'
rainbow_0 = '#cfaf00'
rainbow_1 = '#3f90f0'
rainbow_2 = '#bfaf7a'
rainbow_3 = '#6a9fff'
rainbow_4 = '#aa9f32'
rainbow_5 = '#7fafff'
rainbow_6 = '#af9a6a'
rainbow_7 = '#7a94df'
prose_todo = '#cfaf00'
prose_done = '#009fff'
prose_tag = '#90afef'
prose_table = '#90afef'
err = '#cfaf00'
warning = '#bfaf7a'
info = '#009fff'
hint = '#8aa0df'
ok = '#3fa672'
