# Palette for Ef Elea

[families.ef_elea]
name = 'Ef Elea'
license = 'GPL v3'
light_variant = 'ef_elea_light'
dark_variant = 'ef_elea_dark'

[variants.ef_elea_light]
family = 'ef_elea'
flavor = 'light'
foreground = '#221321'
background = '#edf5e2'
cursor = '#770080'
selection_background = '#d9d2ef'
selection_foreground = '#221321'
ansi = [
  '#edf5e2',
  '#c3303a',
  '#00601f',
  '#9a501f',
  '#375cc6',
  '#80308f',
  '#1f70af',
  '#221321',
  '#e3e9d6',
  '#d00000',
  '#355500',
  '#b04300',
  '#444fcf',
  '#9f356a',
  '#3f6faf',
  '#676470',
]

[variants.ef_elea_light.extended]
none = 'NONE'
bg_main = '#edf5e2'
bg_dim = '#e3e9d6'
bg_alt = '#d0d7ca'
fg_main = '#221321'
fg_dim = '#676470'
fg_alt = '#5f5f1f'
border = '#a5aaaf'
border_highlight = '#5f5f1f'
red = '#c3303a'
red_warmer = '#d00000'
red_cooler = '#b02440'
red_faint = '#894852'
green = '#00601f'
green_warmer = '#355500'
green_cooler = '#007047'
green_faint = '#306630'
yellow = '#9a501f'
yellow_warmer = '#b04300'
yellow_cooler = '#88541f'
yellow_faint = '#7f4f4a'
blue = '#375cc6'
blue_warmer = '#444fcf'
blue_cooler = '#162f8f'
blue_faint = '#3a5099'
magenta = '#80308f'
magenta_warmer = '#9f356a'
magenta_cooler = '#5032aa'
magenta_faint = '#6a4a9f'
cyan = '#1f70af'
cyan_warmer = '#3f6faf'
cyan_cooler = '#00677f'
cyan_faint = '#4f677f'
rust = '#d00000'
gold = '#9a501f'
olive = '#355500'
slate = '#3a5099'
indigo = '#5032aa'
maroon = '#b02440'
pink = '#9f356a'
red_intense = '#c3303a'
green_intense = '#00601f'
yellow_intense = '#9a501f'
blue_intense = '#375cc6'
magenta_intense = '#80308f'
cyan_intense = '#1f70af'
bg_red_intense = '#ff8f88'
bg_green_intense = '#a6df80'
bg_yellow_intense = '#efbf00'
bg_blue_intense = '#cfceff'
bg_magenta_intense = '#df9fff'
bg_cyan_intense = '#88cbdc'
bg_red_subtle = '#f0c6bf'
bg_green_subtle = '#c0e8a7'
bg_yellow_subtle = '#e4e48f'
bg_blue_subtle = '#c9d8f3'
bg_magenta_subtle = '#edd2f0'
bg_cyan_subtle = '#b7e4f0'
bg_red_nuanced = '#f0c6bf'
bg_green_nuanced = '#c0e8a7'
bg_yellow_nuanced = '#e4e48f'
bg_blue_nuanced = '#c9d8f3'
bg_magenta_nuanced = '#edd2f0'
bg_cyan_nuanced = '#b7e4f0'
bg_completion = '#c2eaba'
bg_hl_line = '#d0e7c4'
bg_paren_match = '#8ad3a2'
bg_paren_expression = '#dfbac0'
bg_char_0 = '#c9d8f3'
bg_char_1 = '#edd2f0'
bg_char_2 = '#e4e48f'
bg_active = '#b0b7aa'
fg_active = '#221321'
bg_inactive = '#e8eddc'
fg_inactive = '#676470'
bg_status_line_active = '#a5c67f'
fg_status_line_active = '#142810'
bg_status_line_inactive = '#e3e9d6'
fg_status_line_inactive = '#676470'
bg_tab_bar = '#d0d7ca'
bg_tab_current = '#edf5e2'
bg_tab_other = '#b0b7aa'
fg_tab_other = '#676470'
bg_tab_alternate = '#b5dfbf'
bg_added = '#c7e8ba'
bg_added_faint = '#def0cb'
bg_added_refine = '#bed9b0'
bg_added_fringe = '#bed9b0'
fg_added = '#005000'
fg_added_intense = '#005000'
bg_changed = '#f5e8b0'
bg_changed_faint = '#f5f2bf'
bg_changed_refine = '#f0db9a'
bg_changed_fringe = '#f0db9a'
fg_changed = '#553d00'
fg_changed_intense = '#553d00'
bg_removed = '#f2d0c6'
bg_removed_faint = '#f0e0c0'
bg_removed_refine = '#efbfbd'
bg_removed_fringe = '#efbfbd'
fg_removed = '#8f1313'
fg_removed_intense = '#8f1313'
bg_diff_context = '#e3e9d6'
visual = '#d9d2ef'
link = '#00601f'
link_visited = '#80308f'
link_symbolic = '#1f70af'
string = '#007047'
comment = '#7f4f4a'
constant = '#5032aa'
identifier = '#6a4a9f'
keyword = '#894852'
type = '#162f8f'
fnname = '#355500'
variable = '#80308f'
rainbow_0 = '#355500'
rainbow_1 = '#894852'
rainbow_2 = '#306630'
rainbow_3 = '#00677f'
rainbow_4 = '#5032aa'
rainbow_5 = '#9f356a'
rainbow_6 = '#00601f'
rainbow_7 = '#9a501f'
prose_todo = '#c3303a'
prose_done = '#007047'
prose_tag = '#4f677f'
prose_table = '#5f5f1f'
err = '#d00000'
warning = '#b04300'
info = '#007047'
hint = '#4f677f'
ok = '#007047'

[variants.ef_elea_dark]
family = 'ef_elea'
flavor = 'dark'
foreground = '#eaf2ef'
background = '#222524'
cursor = '#ef7fa8'
selection_background = '#543040'
selection_foreground = '#eaf2ef'
ansi = [
  '#222524',
  '#ff656a',
  '#7fc87f',
  '#cac85f',
  '#57aff6',
  '#f59acf',
  '#6fcfd2',
  '#eaf2ef',
  '#303332',
  '#ff7a5f',
  '#7fca5a',
  '#e0b02f',
  '#78afff',
  '#fa90ea',
  '#7fcfdf',
  '#969faf',
]

[variants.ef_elea_dark.extended]
none = 'NONE'
bg_main = '#222524'
bg_dim = '#303332'
bg_alt = '#3e4140'
fg_main = '#eaf2ef'
fg_dim = '#969faf'
fg_alt = '#8fcfbb'
border = '#5d5f63'
border_highlight = '#8fcfbb'
red = '#ff656a'
red_warmer = '#ff7a5f'
red_cooler = '#fa7f88'
red_faint = '#eba8a8'
green = '#7fc87f'
green_warmer = '#7fca5a'
green_cooler = '#50cf89'
green_faint = '#a9c99f'
yellow = '#cac85f'
yellow_warmer = '#e0b02f'
yellow_cooler = '#cfb27f'
yellow_faint = '#cac89f'
blue = '#57aff6'
blue_warmer = '#78afff'
blue_cooler = '#62cfef'
blue_faint = '#6ab4ef'
magenta = '#f59acf'
magenta_warmer = '#fa90ea'
magenta_cooler = '#cfaaff'
magenta_faint = '#d0b9f0'
cyan = '#6fcfd2'
cyan_warmer = '#7fcfdf'
cyan_cooler = '#60d5c2'
cyan_faint = '#99bfcf'
rust = '#ff7a5f'
gold = '#cac85f'
olive = '#7fca5a'
slate = '#6ab4ef'
indigo = '#cfaaff'
maroon = '#fa7f88'
pink = '#fa90ea'
red_intense = '#ff656a'
green_intense = '#7fc87f'
yellow_intense = '#cac85f'
blue_intense = '#57aff6'
magenta_intense = '#f59acf'
cyan_intense = '#6fcfd2'
bg_red_intense = '#bd1f30'
bg_green_intense = '#408420'
bg_yellow_intense = '#847020'
bg_blue_intense = '#2f5f9f'
bg_magenta_intense = '#b05fcf'
bg_cyan_intense = '#028099'
bg_red_subtle = '#6c2a2a'
bg_green_subtle = '#2f532a'
bg_yellow_subtle = '#62432a'
bg_blue_subtle = '#26486c'
bg_magenta_subtle = '#59335b'
bg_cyan_subtle = '#204c60'
bg_red_nuanced = '#6c2a2a'
bg_green_nuanced = '#2f532a'
bg_yellow_nuanced = '#62432a'
bg_blue_nuanced = '#26486c'
bg_magenta_nuanced = '#59335b'
bg_cyan_nuanced = '#204c60'
bg_completion = '#37493f'
bg_hl_line = '#2f413f'
bg_paren_match = '#3f6f5f'
bg_paren_expression = '#894f7a'
bg_char_0 = '#26486c'
bg_char_1 = '#59335b'
bg_char_2 = '#62432a'
bg_active = '#5e6160'
fg_active = '#eaf2ef'
bg_inactive = '#2b2e2d'
fg_inactive = '#969faf'
bg_status_line_active = '#35605d'
fg_status_line_active = '#ecf0ff'
bg_status_line_inactive = '#303332'
fg_status_line_inactive = '#969faf'
bg_tab_bar = '#3e4140'
bg_tab_current = '#222524'
bg_tab_other = '#5e6160'
fg_tab_other = '#969faf'
bg_tab_alternate = '#425d4a'
bg_added = '#20493f'
bg_added_faint = '#203a2f'
bg_added_refine = '#136244'
bg_added_fringe = '#136244'
fg_added = '#a0e0a0'
fg_added_intense = '#a0e0a0'
bg_changed = '#51512f'
bg_changed_faint = '#40332f'
bg_changed_refine = '#61621f'
bg_changed_fringe = '#61621f'
fg_changed = '#dada90'
fg_changed_intense = '#dada90'
bg_removed = '#5e242f'
bg_removed_faint = '#4a242a'
bg_removed_refine = '#772a35'
bg_removed_fringe = '#772a35'
fg_removed = '#ffbfbf'
fg_removed_intense = '#ffbfbf'
bg_diff_context = '#303332'
visual = '#543040'
link = '#7fca5a'
link_visited = '#f59acf'
link_symbolic = '#6fcfd2'
string = '#50cf89'
comment = '#cac89f'
constant = '#cfaaff'
identifier = '#d0b9f0'
keyword = '#eba8a8'
type = '#6fcfd2'
fnname = '#7fca5a'
variable = '#f59acf'
rainbow_0 = '#7fca5a'
rainbow_1 = '#eba8a8'
rainbow_2 = '#a9c99f'
rainbow_3 = '#60d5c2'
rainbow_4 = '#cfaaff'
rainbow_5 = '#f59acf'
rainbow_6 = '#7fc87f'
rainbow_7 = '#cfb27f'
prose_todo = '#ff7a5f'
prose_done = '#7fca5a'
prose_tag = '#99bfcf'
prose_table = '#8fcfbb'
err = '#ff7a5f'
warning = '#e0b02f'
info = '#50cf89'
hint = '#99bfcf'
ok = '#50cf89'
