# Palette for Ef Light/Dark

[families.ef_lightdark]
name = 'Ef Light/Dark'
license = 'GPL v3'
light_variant = 'ef_light'
dark_variant = 'ef_dark'

[variants.ef_light]
family = 'ef_lightdark'
flavor = 'light'
foreground = '#202020'
background = '#ffffff'
cursor = '#0033cc'
selection_background = '#bfefff'
selection_foreground = '#202020'
ansi = [
  '#ffffff',
  '#d3303a',
  '#217a3c',
  '#a45f22',
  '#3740cf',
  '#ba35af',
  '#1f6fbf',
  '#202020',
  '#efefef',
  '#e00033',
  '#4a7d00',
  '#b6532f',
  '#4250ef',
  '#cf25aa',
  '#3f6faf',
  '#68759f',
]

[variants.ef_light.extended]
none = 'NONE'
bg_main = '#ffffff'
bg_dim = '#efefef'
bg_alt = '#dbdbdb'
fg_main = '#202020'
fg_dim = '#68759f'
fg_alt = '#397a70'
border = '#bfc4da'
border_highlight = '#397a70'
red = '#d3303a'
red_warmer = '#e00033'
red_cooler = '#d51272'
red_faint = '#c24552'
green = '#217a3c'
green_warmer = '#4a7d00'
green_cooler = '#008858'
green_faint = '#61756c'
yellow = '#a45f22'
yellow_warmer = '#b6532f'
yellow_cooler = '#b65050'
yellow_faint = '#a65f6a'
blue = '#3740cf'
blue_warmer = '#4250ef'
blue_cooler = '#065fff'
blue_faint = '#4f54aa'
magenta = '#ba35af'
magenta_warmer = '#cf25aa'
magenta_cooler = '#6052cf'
magenta_faint = '#af5a80'
cyan = '#1f6fbf'
cyan_warmer = '#3f6faf'
cyan_cooler = '#1f77bb'
cyan_faint = '#506fa0'
rust = '#e00033'
gold = '#a45f22'
olive = '#4a7d00'
slate = '#4f54aa'
indigo = '#6052cf'
maroon = '#d51272'
pink = '#cf25aa'
red_intense = '#d3303a'
green_intense = '#217a3c'
yellow_intense = '#a45f22'
blue_intense = '#3740cf'
magenta_intense = '#ba35af'
cyan_intense = '#1f6fbf'
bg_red_intense = '#ff8f88'
bg_green_intense = '#9adf90'
bg_yellow_intense = '#fac200'
bg_blue_intense = '#cbcfff'
bg_magenta_intense = '#df8fff'
bg_cyan_intense = '#88c8ff'
bg_red_subtle = '#ffcfbf'
bg_green_subtle = '#b3fabf'
bg_yellow_subtle = '#fff576'
bg_blue_subtle = '#ccdfff'
bg_magenta_subtle = '#ffddff'
bg_cyan_subtle = '#bfefff'
bg_red_nuanced = '#ffcfbf'
bg_green_nuanced = '#b3fabf'
bg_yellow_nuanced = '#fff576'
bg_blue_nuanced = '#ccdfff'
bg_magenta_nuanced = '#ffddff'
bg_cyan_nuanced = '#bfefff'
bg_completion = '#bfe8ff'
bg_hl_line = '#e4efd8'
bg_paren_match = '#dfa0f3'
bg_paren_expression = '#aaeccf'
bg_char_0 = '#ccdfff'
bg_char_1 = '#ffddff'
bg_char_2 = '#fff576'
bg_active = '#b3b3b3'
fg_active = '#202020'
bg_inactive = '#f9f9f9'
fg_inactive = '#68759f'
bg_status_line_active = '#b7c7ff'
fg_status_line_active = '#151515'
bg_status_line_inactive = '#efefef'
fg_status_line_inactive = '#68759f'
bg_tab_bar = '#dbdbdb'
bg_tab_current = '#ffffff'
bg_tab_other = '#b3b3b3'
fg_tab_other = '#68759f'
bg_tab_alternate = '#ccbfff'
bg_added = '#d0f0d0'
bg_added_faint = '#e5ffe5'
bg_added_refine = '#b2e8be'
bg_added_fringe = '#b2e8be'
fg_added = '#005000'
fg_added_intense = '#005000'
bg_changed = '#f4e8bd'
bg_changed_faint = '#f9efcb'
bg_changed_refine = '#efd299'
bg_changed_fringe = '#efd299'
fg_changed = '#553d00'
fg_changed_intense = '#553d00'
bg_removed = '#ffd8d5'
bg_removed_faint = '#ffe9e9'
bg_removed_refine = '#f3b5af'
bg_removed_fringe = '#f3b5af'
fg_removed = '#8f1313'
fg_removed_intense = '#8f1313'
bg_diff_context = '#efefef'
visual = '#bfefff'
link = '#4250ef'
link_visited = '#ba35af'
link_symbolic = '#1f6fbf'
string = '#4250ef'
comment = '#a65f6a'
constant = '#065fff'
identifier = '#af5a80'
keyword = '#6052cf'
type = '#008858'
fnname = '#cf25aa'
variable = '#1f77bb'
rainbow_0 = '#008858'
rainbow_1 = '#4f54aa'
rainbow_2 = '#ba35af'
rainbow_3 = '#1f77bb'
rainbow_4 = '#b65050'
rainbow_5 = '#6052cf'
rainbow_6 = '#d51272'
rainbow_7 = '#008858'
prose_todo = '#e00033'
prose_done = '#217a3c'
prose_tag = '#61756c'
prose_table = '#397a70'
err = '#e00033'
warning = '#b6532f'
info = '#217a3c'
hint = '#506fa0'
ok = '#008858'

[variants.ef_dark]
family = 'ef_lightdark'
flavor = 'dark'
foreground = '#d0d0d0'
background = '#000000'
cursor = '#ff76ff'
selection_background = '#2a234a'
selection_foreground = '#d0d0d0'
ansi = [
  '#000000',
  '#ef6560',
  '#0faa26',
  '#bf9032',
  '#3f95f6',
  '#d369af',
  '#4fbaef',
  '#d0d0d0',
  '#1a1a1a',
  '#f47360',
  '#6aad0f',
  '#d1843f',
  '#6a9fff',
  '#e580ea',
  '#6fafff',
  '#857f8f',
]

[variants.ef_dark.extended]
none = 'NONE'
bg_main = '#000000'
bg_dim = '#1a1a1a'
bg_alt = '#2b2b2b'
fg_main = '#d0d0d0'
fg_dim = '#857f8f'
fg_alt = '#89afef'
border = '#4f4f5f'
border_highlight = '#89afef'
red = '#ef6560'
red_warmer = '#f47360'
red_cooler = '#ff5a7a'
red_faint = '#d56f72'
green = '#0faa26'
green_warmer = '#6aad0f'
green_cooler = '#00a692'
green_faint = '#61a06c'
yellow = '#bf9032'
yellow_warmer = '#d1843f'
yellow_cooler = '#df8a5a'
yellow_faint = '#cf9f8f'
blue = '#3f95f6'
blue_warmer = '#6a9fff'
blue_cooler = '#029fff'
blue_faint = '#7a94df'
magenta = '#d369af'
magenta_warmer = '#e580ea'
magenta_cooler = '#af85ff'
magenta_faint = '#c58faf'
cyan = '#4fbaef'
cyan_warmer = '#6fafff'
cyan_cooler = '#1dbfcf'
cyan_faint = '#8aa0df'
rust = '#f47360'
gold = '#bf9032'
olive = '#6aad0f'
slate = '#7a94df'
indigo = '#af85ff'
maroon = '#ff5a7a'
pink = '#e580ea'
red_intense = '#ef6560'
green_intense = '#0faa26'
yellow_intense = '#bf9032'
blue_intense = '#3f95f6'
magenta_intense = '#d369af'
cyan_intense = '#4fbaef'
bg_red_intense = '#b02930'
bg_green_intense = '#337133'
bg_yellow_intense = '#8f5040'
bg_blue_intense = '#4648d0'
bg_magenta_intense = '#804fdd'
bg_cyan_intense = '#2270cf'
bg_red_subtle = '#72002a'
bg_green_subtle = '#00422a'
bg_yellow_subtle = '#603000'
bg_blue_subtle = '#2f2f74'
bg_magenta_subtle = '#572060'
bg_cyan_subtle = '#004065'
bg_red_nuanced = '#72002a'
bg_green_nuanced = '#00422a'
bg_yellow_nuanced = '#603000'
bg_blue_nuanced = '#2f2f74'
bg_magenta_nuanced = '#572060'
bg_cyan_nuanced = '#004065'
bg_completion = '#0f2d4a'
bg_hl_line = '#002435'
bg_paren_match = '#20577a'
bg_paren_expression = '#004a5f'
bg_char_0 = '#2f2f74'
bg_char_1 = '#572060'
bg_char_2 = '#603000'
bg_active = '#4b4b4b'
fg_active = '#d0d0d0'
bg_inactive = '#121212'
fg_inactive = '#857f8f'
bg_status_line_active = '#2a2a75'
fg_status_line_active = '#e0e0ff'
bg_status_line_inactive = '#1a1a1a'
fg_status_line_inactive = '#857f8f'
bg_tab_bar = '#2b2b2b'
bg_tab_current = '#000000'
bg_tab_other = '#4b4b4b'
fg_tab_other = '#857f8f'
bg_tab_alternate = '#551f5a'
bg_added = '#00381f'
bg_added_faint = '#002910'
bg_added_refine = '#034f2f'
bg_added_fringe = '#034f2f'
fg_added = '#a0e0a0'
fg_added_intense = '#a0e0a0'
bg_changed = '#363300'
bg_changed_faint = '#2a1f00'
bg_changed_refine = '#4a4a00'
bg_changed_fringe = '#4a4a00'
fg_changed = '#efef80'
fg_changed_intense = '#efef80'
bg_removed = '#4f1119'
bg_removed_faint = '#380a0f'
bg_removed_refine = '#781a1f'
bg_removed_fringe = '#781a1f'
fg_removed = '#ffbfbf'
fg_removed_intense = '#ffbfbf'
bg_diff_context = '#1a1a1a'
visual = '#2a234a'
link = '#4fbaef'
link_visited = '#d369af'
link_symbolic = '#4fbaef'
string = '#6a9fff'
comment = '#cf9f8f'
constant = '#029fff'
identifier = '#c58faf'
keyword = '#af85ff'
type = '#00a692'
fnname = '#e580ea'
variable = '#1dbfcf'
rainbow_0 = '#00a692'
rainbow_1 = '#3f95f6'
rainbow_2 = '#e580ea'
rainbow_3 = '#1dbfcf'
rainbow_4 = '#df8a5a'
rainbow_5 = '#af85ff'
rainbow_6 = '#ff5a7a'
rainbow_7 = '#6aad0f'
prose_todo = '#f47360'
prose_done = '#0faa26'
prose_tag = '#cf9f8f'
prose_table = '#89afef'
err = '#f47360'
warning = '#bf9032'
info = '#0faa26'
hint = '#8aa0df'
ok = '#00a692'
