# Palette for Ef Melissa

[families.ef_melissa]
name = 'Ef Melissa'
license = 'GPL v3'
light_variant = 'ef_melissa_light'
dark_variant = 'ef_melissa_dark'

[variants.ef_melissa_light]
family = 'ef_melissa'
flavor = 'light'
foreground = '#484431'
background = '#fff6d8'
cursor = '#a07f00'
selection_background = '#f0d4d8'
selection_foreground = '#484431'
ansi = [
  '#fff6d8',
  '#ba2d2f',
  '#007a0a',
  '#a26310',
  '#375cc6',
  '#aa3e74',
  '#3f60af',
  '#484431',
  '#f5e9cb',
  '#c74400',
  '#5a7400',
  '#ba5205',
  '#5f5fdf',
  '#b02f80',
  '#4060a0',
  '#68708a',
]

[variants.ef_melissa_light.extended]
none = 'NONE'
bg_main = '#fff6d8'
bg_dim = '#f5e9cb'
bg_alt = '#e7d7c6'
fg_main = '#484431'
fg_dim = '#68708a'
fg_alt = '#80431a'
border = '#c5baa6'
border_highlight = '#80431a'
red = '#ba2d2f'
red_warmer = '#c74400'
red_cooler = '#c02945'
red_faint = '#b05350'
green = '#007a0a'
green_warmer = '#5a7400'
green_cooler = '#008250'
green_faint = '#61756c'
yellow = '#a26310'
yellow_warmer = '#ba5205'
yellow_cooler = '#946830'
yellow_faint = '#7f6f1a'
blue = '#375cc6'
blue_warmer = '#5f5fdf'
blue_cooler = '#265fbf'
blue_faint = '#4a659f'
magenta = '#aa3e74'
magenta_warmer = '#b02f80'
magenta_cooler = '#6448ca'
magenta_faint = '#905ea0'
cyan = '#3f60af'
cyan_warmer = '#4060a0'
cyan_cooler = '#0f708a'
cyan_faint = '#4f6f8f'
rust = '#c74400'
gold = '#a26310'
olive = '#5a7400'
slate = '#4a659f'
indigo = '#6448ca'
maroon = '#c02945'
pink = '#b02f80'
red_intense = '#ba2d2f'
green_intense = '#007a0a'
yellow_intense = '#a26310'
blue_intense = '#375cc6'
magenta_intense = '#aa3e74'
cyan_intense = '#3f60af'
bg_red_intense = '#ff8f88'
bg_green_intense = '#96df80'
bg_yellow_intense = '#efbf00'
bg_blue_intense = '#cfceff'
bg_magenta_intense = '#df9fff'
bg_cyan_intense = '#88cfd0'
bg_red_subtle = '#ffceb0'
bg_green_subtle = '#cbf09f'
bg_yellow_subtle = '#f4ed7e'
bg_blue_subtle = '#cce4f2'
bg_magenta_subtle = '#fad6ef'
bg_cyan_subtle = '#bfefef'
bg_red_nuanced = '#ffceb0'
bg_green_nuanced = '#cbf09f'
bg_yellow_nuanced = '#f4ed7e'
bg_blue_nuanced = '#cce4f2'
bg_magenta_nuanced = '#fad6ef'
bg_cyan_nuanced = '#bfefef'
bg_completion = '#ffe2a8'
bg_hl_line = '#fae7b0'
bg_paren_match = '#afcf8f'
bg_paren_expression = '#deb4f0'
bg_char_0 = '#cce4f2'
bg_char_1 = '#fad6ef'
bg_char_2 = '#f4ed7e'
bg_active = '#c7b7a6'
fg_active = '#484431'
bg_inactive = '#f9efd4'
fg_inactive = '#68708a'
bg_status_line_active = '#f3cf72'
fg_status_line_active = '#403328'
bg_status_line_inactive = '#f5e9cb'
fg_status_line_inactive = '#68708a'
bg_tab_bar = '#e7d7c6'
bg_tab_current = '#fff6d8'
bg_tab_other = '#f5e9cb'
fg_tab_other = '#68708a'
bg_tab_alternate = '#c4d47a'
bg_added = '#d7ecb0'
bg_added_faint = '#eef3c2'
bg_added_refine = '#c9dda0'
bg_added_fringe = '#c9dda0'
fg_added = '#005000'
fg_added_intense = '#005000'
bg_changed = '#f5e690'
bg_changed_faint = '#f5edaf'
bg_changed_refine = '#edd482'
bg_changed_fringe = '#edd482'
fg_changed = '#553d00'
fg_changed_intense = '#553d00'
bg_removed = '#f8d0b6'
bg_removed_faint = '#f5deb0'
bg_removed_refine = '#f0bba9'
bg_removed_fringe = '#f0bba9'
fg_removed = '#8f1313'
fg_removed_intense = '#8f1313'
bg_diff_context = '#f5e9cb'
visual = '#f0d4d8'
link = '#a26310'
link_visited = '#6448ca'
link_symbolic = '#3f60af'
string = '#c74400'
comment = '#7f6f1a'
constant = '#3f60af'
identifier = '#b05350'
keyword = '#a26310'
type = '#008250'
fnname = '#5a7400'
variable = '#0f708a'
rainbow_0 = '#ba5205'
rainbow_1 = '#a26310'
rainbow_2 = '#5a7400'
rainbow_3 = '#c02945'
rainbow_4 = '#4060a0'
rainbow_5 = '#aa3e74'
rainbow_6 = '#008250'
rainbow_7 = '#b02f80'
prose_todo = '#c74400'
prose_done = '#007a0a'
prose_tag = '#7f6f1a'
prose_table = '#80431a'
err = '#c74400'
warning = '#ba5205'
info = '#007a0a'
hint = '#4f6f8f'
ok = '#008250'

[variants.ef_melissa_dark]
family = 'ef_melissa'
flavor = 'dark'
foreground = '#e8e4b1'
background = '#352718'
cursor = '#f9cf7a'
selection_background = '#443a4f'
selection_foreground = '#e8e4b1'
ansi = [
  '#352718',
  '#ff7f7f',
  '#6fd560',
  '#e4b53f',
  '#57aff6',
  '#f0aac5',
  '#6fcad0',
  '#e8e4b1',
  '#483426',
  '#ff7f4f',
  '#a0d13a',
  '#ffa21f',
  '#98bfff',
  '#fa90aa',
  '#7fc5df',
  '#90918a',
]

[variants.ef_melissa_dark.extended]
none = 'NONE'
bg_main = '#352718'
bg_dim = '#483426'
bg_alt = '#59463f'
fg_main = '#e8e4b1'
fg_dim = '#90918a'
fg_alt = '#ccaa70'
border = '#6f5f58'
border_highlight = '#ccaa70'
red = '#ff7f7f'
red_warmer = '#ff7f4f'
red_cooler = '#ff8f98'
red_faint = '#e89a88'
green = '#6fd560'
green_warmer = '#a0d13a'
green_cooler = '#65d590'
green_faint = '#a0d26f'
yellow = '#e4b53f'
yellow_warmer = '#ffa21f'
yellow_cooler = '#e7a06f'
yellow_faint = '#eab780'
blue = '#57aff6'
blue_warmer = '#98bfff'
blue_cooler = '#62cfef'
blue_faint = '#6ab4ef'
magenta = '#f0aac5'
magenta_warmer = '#fa90aa'
magenta_cooler = '#c6a2fe'
magenta_faint = '#dfcfe0'
cyan = '#6fcad0'
cyan_warmer = '#7fc5df'
cyan_cooler = '#70e0cf'
cyan_faint = '#99bfcf'
rust = '#ff7f4f'
gold = '#e4b53f'
olive = '#a0d13a'
slate = '#6ab4ef'
indigo = '#c6a2fe'
maroon = '#ff8f98'
pink = '#fa90aa'
red_intense = '#ff7f7f'
green_intense = '#6fd560'
yellow_intense = '#e4b53f'
blue_intense = '#57aff6'
magenta_intense = '#f0aac5'
cyan_intense = '#6fcad0'
bg_red_intense = '#b02930'
bg_green_intense = '#4a7100'
bg_yellow_intense = '#8f5040'
bg_blue_intense = '#4648d0'
bg_magenta_intense = '#a04fc5'
bg_cyan_intense = '#2270cf'
bg_red_subtle = '#72292a'
bg_green_subtle = '#3f521a'
bg_yellow_subtle = '#604b13'
bg_blue_subtle = '#384862'
bg_magenta_subtle = '#613a50'
bg_cyan_subtle = '#2f4f4f'
bg_red_nuanced = '#72292a'
bg_green_nuanced = '#3f521a'
bg_yellow_nuanced = '#604b13'
bg_blue_nuanced = '#384862'
bg_magenta_nuanced = '#613a50'
bg_cyan_nuanced = '#2f4f4f'
bg_completion = '#66421f'
bg_hl_line = '#4f311f'
bg_paren_match = '#5f6f1f'
bg_paren_expression = '#60518f'
bg_char_0 = '#384862'
bg_char_1 = '#613a50'
bg_char_2 = '#604b13'
bg_active = '#79665f'
fg_active = '#e8e4b1'
bg_inactive = '#3d2e1f'
fg_inactive = '#90918a'
bg_status_line_active = '#704f00'
fg_status_line_active = '#f8efd8'
bg_status_line_inactive = '#483426'
fg_status_line_inactive = '#90918a'
bg_tab_bar = '#59463f'
bg_tab_current = '#352718'
bg_tab_other = '#483426'
fg_tab_other = '#90918a'
bg_tab_alternate = '#5a661f'
bg_added = '#2f491f'
bg_added_faint = '#2f3b0f'
bg_added_refine = '#3f6234'
bg_added_fringe = '#3f6234'
fg_added = '#a0e0a0'
fg_added_intense = '#a0e0a0'
bg_changed = '#544a0f'
bg_changed_faint = '#43350f'
bg_changed_refine = '#615f1f'
bg_changed_fringe = '#615f1f'
fg_changed = '#dada90'
fg_changed_intense = '#dada90'
bg_removed = '#622a1f'
bg_removed_faint = '#4b240a'
bg_removed_refine = '#7f3325'
bg_removed_fringe = '#7f3325'
fg_removed = '#ffbfbf'
fg_removed_intense = '#ffbfbf'
bg_diff_context = '#483426'
visual = '#443a4f'
link = '#e4b53f'
link_visited = '#c6a2fe'
link_symbolic = '#6fcad0'
string = '#ffa21f'
comment = '#eab780'
constant = '#98bfff'
identifier = '#e89a88'
keyword = '#e4b53f'
type = '#65d590'
fnname = '#6fd560'
variable = '#6fcad0'
rainbow_0 = '#ffa21f'
rainbow_1 = '#e4b53f'
rainbow_2 = '#a0d13a'
rainbow_3 = '#ff8f98'
rainbow_4 = '#7fc5df'
rainbow_5 = '#f0aac5'
rainbow_6 = '#65d590'
rainbow_7 = '#fa90aa'
prose_todo = '#ff7f4f'
prose_done = '#6fd560'
prose_tag = '#eab780'
prose_table = '#ccaa70'
err = '#ff7f4f'
warning = '#ffa21f'
info = '#6fd560'
hint = '#99bfcf'
ok = '#65d590'
