# Palette for Ef Maris

[families.ef_maris]
name = 'Ef Maris'
license = 'GPL v3'
light_variant = 'ef_maris_light'
dark_variant = 'ef_maris_dark'

[variants.ef_maris_light]
family = 'ef_maris'
flavor = 'light'
foreground = '#151a27'
background = '#edf4f8'
cursor = '#036f99'
selection_background = '#c8dcff'
selection_foreground = '#151a27'
ansi = [
  '#edf4f8',
  '#c3303a',
  '#007010',
  '#805a1f',
  '#375cc6',
  '#80308f',
  '#1f66af',
  '#151a27',
  '#e0e7ef',
  '#d00000',
  '#3a6f00',
  '#8b4400',
  '#444fcf',
  '#9a3a6a',
  '#305675',
  '#676470',
]

[variants.ef_maris_light.extended]
none = 'NONE'
bg_main = '#edf4f8'
bg_dim = '#e0e7ef'
bg_alt = '#cfd8e3'
fg_main = '#151a27'
fg_dim = '#676470'
fg_alt = '#3f4f99'
border = '#a2a6af'
border_highlight = '#3f4f99'
red = '#c3303a'
red_warmer = '#d00000'
red_cooler = '#b02440'
red_faint = '#8b4052'
green = '#007010'
green_warmer = '#3a6f00'
green_cooler = '#007047'
green_faint = '#4a763f'
yellow = '#805a1f'
yellow_warmer = '#8b4400'
yellow_cooler = '#78542f'
yellow_faint = '#7f4f4a'
blue = '#375cc6'
blue_warmer = '#444fcf'
blue_cooler = '#003faf'
blue_faint = '#3a5099'
magenta = '#80308f'
magenta_warmer = '#9a3a6a'
magenta_cooler = '#5f2fba'
magenta_faint = '#6a4a9f'
cyan = '#1f66af'
cyan_warmer = '#305675'
cyan_cooler = '#006f70'
cyan_faint = '#3f627f'
rust = '#d00000'
gold = '#805a1f'
olive = '#3a6f00'
slate = '#3a5099'
indigo = '#5f2fba'
maroon = '#b02440'
pink = '#9a3a6a'
red_intense = '#c3303a'
green_intense = '#007010'
yellow_intense = '#805a1f'
blue_intense = '#375cc6'
magenta_intense = '#80308f'
cyan_intense = '#1f66af'
bg_red_intense = '#ff8f88'
bg_green_intense = '#96df80'
bg_yellow_intense = '#efbf00'
bg_blue_intense = '#cfceff'
bg_magenta_intense = '#df9fff'
bg_cyan_intense = '#88cfd0'
bg_red_subtle = '#f0c6cf'
bg_green_subtle = '#b0ebca'
bg_yellow_subtle = '#e4e498'
bg_blue_subtle = '#ccd5f7'
bg_magenta_subtle = '#edd3f2'
bg_cyan_subtle = '#b2e6f0'
bg_red_nuanced = '#f0c6cf'
bg_green_nuanced = '#b0ebca'
bg_yellow_nuanced = '#e4e498'
bg_blue_nuanced = '#ccd5f7'
bg_magenta_nuanced = '#edd3f2'
bg_cyan_nuanced = '#b2e6f0'
bg_completion = '#cddbfa'
bg_hl_line = '#dae5f0'
bg_paren_match = '#cab3b2'
bg_paren_expression = '#d2b4cf'
bg_char_0 = '#ccd5f7'
bg_char_1 = '#edd3f2'
bg_char_2 = '#e4e498'
bg_active = '#afb8c3'
fg_active = '#151a27'
bg_inactive = '#e6ecf2'
fg_inactive = '#676470'
bg_status_line_active = '#a0c2ef'
fg_status_line_active = '#142810'
bg_status_line_inactive = '#e0e7ef'
fg_status_line_inactive = '#676470'
bg_tab_bar = '#cfd8e3'
bg_tab_current = '#edf4f8'
bg_tab_other = '#afb8c3'
fg_tab_other = '#676470'
bg_tab_alternate = '#b7bbea'
bg_added = '#b0e8ca'
bg_added_faint = '#c5f0e0'
bg_added_refine = '#a0d4b9'
bg_added_fringe = '#a0d4b9'
fg_added = '#005000'
fg_added_intense = '#005000'
bg_changed = '#f5e8b0'
bg_changed_faint = '#f5f2bf'
bg_changed_refine = '#f0db9a'
bg_changed_fringe = '#f0db9a'
fg_changed = '#553d00'
fg_changed_intense = '#553d00'
bg_removed = '#f5c7d6'
bg_removed_faint = '#f0d6d6'
bg_removed_refine = '#efb1cd'
bg_removed_fringe = '#efb1cd'
fg_removed = '#8f1313'
fg_removed_intense = '#8f1313'
bg_diff_context = '#e0e7ef'
visual = '#c8dcff'
link = '#375cc6'
link_visited = '#5f2fba'
link_symbolic = '#1f66af'
string = '#006f70'
comment = '#8b4052'
constant = '#003faf'
identifier = '#6a4a9f'
keyword = '#444fcf'
type = '#007010'
fnname = '#3a6f00'
variable = '#1f66af'
rainbow_0 = '#007047'
rainbow_1 = '#444fcf'
rainbow_2 = '#3a6f00'
rainbow_3 = '#1f66af'
rainbow_4 = '#5f2fba'
rainbow_5 = '#003faf'
rainbow_6 = '#80308f'
rainbow_7 = '#006f70'
prose_todo = '#b02440'
prose_done = '#007047'
prose_tag = '#3f627f'
prose_table = '#3f4f99'
err = '#d00000'
warning = '#8b4400'
info = '#007047'
hint = '#3f627f'
ok = '#007047'

[variants.ef_maris_dark]
family = 'ef_maris'
flavor = 'dark'
foreground = '#eaedef'
background = '#131c2b'
cursor = '#8fdfff'
selection_background = '#183c65'
selection_foreground = '#eaedef'
ansi = [
  '#131c2b',
  '#ff6f6f',
  '#41bf4f',
  '#d0d24f',
  '#57b0ff',
  '#f59acf',
  '#2fd0db',
  '#eaedef',
  '#1d2c39',
  '#ff7a5f',
  '#7fce5f',
  '#f0c060',
  '#70a0ff',
  '#fa90ea',
  '#7fcfdf',
  '#969faf',
]

[variants.ef_maris_dark.extended]
none = 'NONE'
bg_main = '#131c2b'
bg_dim = '#1d2c39'
bg_alt = '#2a3644'
fg_main = '#eaedef'
fg_dim = '#969faf'
fg_alt = '#90a0dc'
border = '#595a63'
border_highlight = '#90a0dc'
red = '#ff6f6f'
red_warmer = '#ff7a5f'
red_cooler = '#ff7788'
red_faint = '#eaa4a4'
green = '#41bf4f'
green_warmer = '#7fce5f'
green_cooler = '#30c489'
green_faint = '#a9c99f'
yellow = '#d0d24f'
yellow_warmer = '#f0c060'
yellow_cooler = '#cab27f'
yellow_faint = '#cac89f'
blue = '#57b0ff'
blue_warmer = '#70a0ff'
blue_cooler = '#12b4ff'
blue_faint = '#9acfff'
magenta = '#f59acf'
magenta_warmer = '#fa90ea'
magenta_cooler = '#cf90ff'
magenta_faint = '#d4aaf0'
cyan = '#2fd0db'
cyan_warmer = '#7fcfdf'
cyan_cooler = '#65d5a8'
cyan_faint = '#99bfcf'
rust = '#ff7a5f'
gold = '#d0d24f'
olive = '#7fce5f'
slate = '#9acfff'
indigo = '#cf90ff'
maroon = '#ff7788'
pink = '#fa90ea'
red_intense = '#ff6f6f'
green_intense = '#41bf4f'
yellow_intense = '#d0d24f'
blue_intense = '#57b0ff'
magenta_intense = '#f59acf'
cyan_intense = '#2fd0db'
bg_red_intense = '#bd1f30'
bg_green_intense = '#107840'
bg_yellow_intense = '#847020'
bg_blue_intense = '#2f5f9f'
bg_magenta_intense = '#b05fcf'
bg_cyan_intense = '#0280b9'
bg_red_subtle = '#6f293a'
bg_green_subtle = '#1f523a'
bg_yellow_subtle = '#604233'
bg_blue_subtle = '#284477'
bg_magenta_subtle = '#52336b'
bg_cyan_subtle = '#204c68'
bg_red_nuanced = '#6f293a'
bg_green_nuanced = '#1f523a'
bg_yellow_nuanced = '#604233'
bg_blue_nuanced = '#284477'
bg_magenta_nuanced = '#52336b'
bg_cyan_nuanced = '#204c68'
bg_completion = '#204358'
bg_hl_line = '#243242'
bg_paren_match = '#6c5d54'
bg_paren_expression = '#684d54'
bg_char_0 = '#284477'
bg_char_1 = '#52336b'
bg_char_2 = '#604233'
bg_active = '#4a5664'
fg_active = '#eaedef'
bg_inactive = '#1a2331'
fg_inactive = '#969faf'
bg_status_line_active = '#2f527b'
fg_status_line_active = '#ecf0ff'
bg_status_line_inactive = '#1d2c39'
fg_status_line_inactive = '#969faf'
bg_tab_bar = '#2a3644'
bg_tab_current = '#131c2b'
bg_tab_other = '#4a5664'
fg_tab_other = '#969faf'
bg_tab_alternate = '#49516a'
bg_added = '#20493f'
bg_added_faint = '#163530'
bg_added_refine = '#136244'
bg_added_fringe = '#136244'
fg_added = '#a0e0a0'
fg_added_intense = '#a0e0a0'
bg_changed = '#51512f'
bg_changed_faint = '#40332f'
bg_changed_refine = '#61621f'
bg_changed_fringe = '#61621f'
fg_changed = '#dada90'
fg_changed_intense = '#dada90'
bg_removed = '#5e242f'
bg_removed_faint = '#4a202d'
bg_removed_refine = '#772a35'
bg_removed_fringe = '#772a35'
fg_removed = '#ffbfbf'
fg_removed_intense = '#ffbfbf'
bg_diff_context = '#1d2c39'
visual = '#183c65'
link = '#57b0ff'
link_visited = '#cf90ff'
link_symbolic = '#2fd0db'
string = '#65d5a8'
comment = '#eaa4a4'
constant = '#12b4ff'
identifier = '#d4aaf0'
keyword = '#70a0ff'
type = '#41bf4f'
fnname = '#7fce5f'
variable = '#2fd0db'
rainbow_0 = '#30c489'
rainbow_1 = '#70a0ff'
rainbow_2 = '#7fce5f'
rainbow_3 = '#2fd0db'
rainbow_4 = '#cf90ff'
rainbow_5 = '#12b4ff'
rainbow_6 = '#f59acf'
rainbow_7 = '#65d5a8'
prose_todo = '#ff7788'
prose_done = '#30c489'
prose_tag = '#99bfcf'
prose_table = '#90a0dc'
err = '#ff7a5f'
warning = '#f0c060'
info = '#30c489'
hint = '#99bfcf'
ok = '#30c489'
