# Palette for Ef Trio

[families.ef_trio]
name = 'Ef Trio'
license = 'GPL v3'
light_variant = 'ef_trio_light'
dark_variant = 'ef_trio_dark'

[variants.ef_trio_light]
family = 'ef_trio'
flavor = 'light'
foreground = '#4f3363'
background = '#f8f5ff'
cursor = '#4f45ff'
selection_background = '#eed0ff'
selection_foreground = '#4f3363'
ansi = [
  '#f8f5ff',
  '#c3303a',
  '#057800',
  '#a45f22',
  '#375cd6',
  '#ad45ba',
  '#1f6fbf',
  '#4f3363',
  '#ebe7f1',
  '#d03033',
  '#4f7d0f',
  '#b8532f',
  '#5165e4',
  '#c035aa',
  '#3f6faf',
  '#786e74',
]

[variants.ef_trio_light.extended]
none = 'NONE'
bg_main = '#f8f5ff'
bg_dim = '#ebe7f1'
bg_alt = '#e3e0e9'
fg_main = '#4f3363'
fg_dim = '#786e74'
fg_alt = '#3f7668'
border = '#c6bac5'
border_highlight = '#3f7668'
red = '#c3303a'
red_warmer = '#d03033'
red_cooler = '#c01f5f'
red_faint = '#a24568'
green = '#057800'
green_warmer = '#4f7d0f'
green_cooler = '#007f6f'
green_faint = '#41754c'
yellow = '#a45f22'
yellow_warmer = '#b8532f'
yellow_cooler = '#b65050'
yellow_faint = '#a05b5f'
blue = '#375cd6'
blue_warmer = '#5165e4'
blue_cooler = '#065fbf'
blue_faint = '#6060d0'
magenta = '#ad45ba'
magenta_warmer = '#c035aa'
magenta_cooler = '#705ae3'
magenta_faint = '#804fb0'
cyan = '#1f6fbf'
cyan_warmer = '#3f6faf'
cyan_cooler = '#0f7a9d'
cyan_faint = '#5f60bf'
rust = '#d03033'
gold = '#a45f22'
olive = '#4f7d0f'
slate = '#6060d0'
indigo = '#705ae3'
maroon = '#c01f5f'
pink = '#c035aa'
red_intense = '#c3303a'
green_intense = '#057800'
yellow_intense = '#a45f22'
blue_intense = '#375cd6'
magenta_intense = '#ad45ba'
cyan_intense = '#1f6fbf'
bg_red_intense = '#ff7f88'
bg_green_intense = '#7fdda0'
bg_yellow_intense = '#ffc200'
bg_blue_intense = '#cbcfff'
bg_magenta_intense = '#df8fff'
bg_cyan_intense = '#88ccff'
bg_red_subtle = '#ffc3c7'
bg_green_subtle = '#beecc2'
bg_yellow_subtle = '#f3ea8f'
bg_blue_subtle = '#ceddff'
bg_magenta_subtle = '#f5cff8'
bg_cyan_subtle = '#c0eaf0'
bg_red_nuanced = '#ffc3c7'
bg_green_nuanced = '#beecc2'
bg_yellow_nuanced = '#f3ea8f'
bg_blue_nuanced = '#ceddff'
bg_magenta_nuanced = '#f5cff8'
bg_cyan_nuanced = '#c0eaf0'
bg_completion = '#f4cfff'
bg_hl_line = '#cfe6ff'
bg_paren_match = '#dfadaf'
bg_paren_expression = '#aaeccf'
bg_char_0 = '#ceddff'
bg_char_1 = '#f5cff8'
bg_char_2 = '#f3ea8f'
bg_active = '#c3c0c9'
fg_active = '#4f3363'
bg_inactive = '#efeef7'
fg_inactive = '#786e74'
bg_status_line_active = '#ddb4ff'
fg_status_line_active = '#241f48'
bg_status_line_inactive = '#ebe7f1'
fg_status_line_inactive = '#786e74'
bg_tab_bar = '#e3e0e9'
bg_tab_current = '#f8f5ff'
bg_tab_other = '#c3c0c9'
fg_tab_other = '#786e74'
bg_tab_alternate = '#b4cfff'
bg_added = '#caf4da'
bg_added_faint = '#dff6ea'
bg_added_refine = '#bae9cf'
bg_added_fringe = '#bae9cf'
fg_added = '#005000'
fg_added_intense = '#005000'
bg_changed = '#ffdfb9'
bg_changed_faint = '#ffefcb'
bg_changed_refine = '#ffcfa0'
bg_changed_fringe = '#ffcfa0'
fg_changed = '#553d00'
fg_changed_intense = '#553d00'
bg_removed = '#ffcee0'
bg_removed_faint = '#ffdfe6'
bg_removed_refine = '#f5b6c8'
bg_removed_fringe = '#f5b6c8'
fg_removed = '#8f1313'
fg_removed_intense = '#8f1313'
bg_diff_context = '#ebe7f1'
visual = '#eed0ff'
link = '#375cd6'
link_visited = '#705ae3'
link_symbolic = '#1f6fbf'
string = '#007f6f'
comment = '#a05b5f'
constant = '#c035aa'
identifier = '#a24568'
keyword = '#ad45ba'
type = '#0f7a9d'
fnname = '#5165e4'
variable = '#3f6faf'
rainbow_0 = '#c035aa'
rainbow_1 = '#5165e4'
rainbow_2 = '#007f6f'
rainbow_3 = '#ad45ba'
rainbow_4 = '#1f6fbf'
rainbow_5 = '#4f7d0f'
rainbow_6 = '#705ae3'
rainbow_7 = '#3f6faf'
prose_todo = '#d03033'
prose_done = '#057800'
prose_tag = '#804fb0'
prose_table = '#3f7668'
err = '#d03033'
warning = '#b8532f'
info = '#057800'
hint = '#5f60bf'
ok = '#007f6f'

[variants.ef_trio_dark]
family = 'ef_trio'
flavor = 'dark'
foreground = '#d8cfd5'
background = '#160f0f'
cursor = '#ff99ff'
selection_background = '#16304f'
selection_foreground = '#d8cfd5'
ansi = [
  '#160f0f',
  '#f48359',
  '#60b444',
  '#d4a052',
  '#7fa5f6',
  '#d37faf',
  '#8fbaff',
  '#d8cfd5',
  '#2a2228',
  '#ff7560',
  '#a0c27f',
  '#ef926f',
  '#8895ff',
  '#e772df',
  '#9ac2ff',
  '#908890',
]

[variants.ef_trio_dark.extended]
none = 'NONE'
bg_main = '#160f0f'
bg_dim = '#2a2228'
bg_alt = '#362f35'
fg_main = '#d8cfd5'
fg_dim = '#908890'
fg_alt = '#afdacf'
border = '#605760'
border_highlight = '#afdacf'
red = '#f48359'
red_warmer = '#ff7560'
red_cooler = '#ff85aa'
red_faint = '#e07a9a'
green = '#60b444'
green_warmer = '#a0c27f'
green_cooler = '#60bf88'
green_faint = '#61a06c'
yellow = '#d4a052'
yellow_warmer = '#ef926f'
yellow_cooler = '#ef9680'
yellow_faint = '#c7a07f'
blue = '#7fa5f6'
blue_warmer = '#8895ff'
blue_cooler = '#72afff'
blue_faint = '#7a94df'
magenta = '#d37faf'
magenta_warmer = '#e772df'
magenta_cooler = '#a698ef'
magenta_faint = '#c9addf'
cyan = '#8fbaff'
cyan_warmer = '#9ac2ff'
cyan_cooler = '#8fcfdf'
cyan_faint = '#8ac0ef'
rust = '#ff7560'
gold = '#d4a052'
olive = '#a0c27f'
slate = '#7a94df'
indigo = '#a698ef'
maroon = '#ff85aa'
pink = '#e772df'
red_intense = '#f48359'
green_intense = '#60b444'
yellow_intense = '#d4a052'
blue_intense = '#7fa5f6'
magenta_intense = '#d37faf'
cyan_intense = '#8fbaff'
bg_red_intense = '#b02930'
bg_green_intense = '#2a7140'
bg_yellow_intense = '#8f5040'
bg_blue_intense = '#4648d0'
bg_magenta_intense = '#804fd5'
bg_cyan_intense = '#2270cf'
bg_red_subtle = '#651f1a'
bg_green_subtle = '#1a421f'
bg_yellow_subtle = '#553320'
bg_blue_subtle = '#283565'
bg_magenta_subtle = '#562654'
bg_cyan_subtle = '#133d58'
bg_red_nuanced = '#651f1a'
bg_green_nuanced = '#1a421f'
bg_yellow_nuanced = '#553320'
bg_blue_nuanced = '#283565'
bg_magenta_nuanced = '#562654'
bg_cyan_nuanced = '#133d58'
bg_completion = '#2f335a'
bg_hl_line = '#34223f'
bg_paren_match = '#2f605e'
bg_paren_expression = '#004f3f'
bg_char_0 = '#283565'
bg_char_1 = '#562654'
bg_char_2 = '#553320'
bg_active = '#564f55'
fg_active = '#d8cfd5'
bg_inactive = '#1c1719'
fg_inactive = '#908890'
bg_status_line_active = '#6a294f'
fg_status_line_active = '#ffdfdf'
bg_status_line_inactive = '#2a2228'
fg_status_line_inactive = '#908890'
bg_tab_bar = '#362f35'
bg_tab_current = '#160f0f'
bg_tab_other = '#564f55'
fg_tab_other = '#908890'
bg_tab_alternate = '#452f5f'
bg_added = '#00371f'
bg_added_faint = '#002918'
bg_added_refine = '#004c2f'
bg_added_fringe = '#004c2f'
fg_added = '#a0e0a0'
fg_added_intense = '#a0e0a0'
bg_changed = '#363300'
bg_changed_faint = '#2a1f00'
bg_changed_refine = '#4a4a00'
bg_changed_fringe = '#4a4a00'
fg_changed = '#efef80'
fg_changed_intense = '#efef80'
bg_removed = '#450f1f'
bg_removed_faint = '#2f060f'
bg_removed_refine = '#641426'
bg_removed_fringe = '#641426'
fg_removed = '#ffbfbf'
fg_removed_intense = '#ffbfbf'
bg_diff_context = '#2a2228'
visual = '#16304f'
link = '#7fa5f6'
link_visited = '#a698ef'
link_symbolic = '#8fbaff'
string = '#60bf88'
comment = '#c7a07f'
constant = '#e772df'
identifier = '#e07a9a'
keyword = '#d37faf'
type = '#8fcfdf'
fnname = '#8895ff'
variable = '#9ac2ff'
rainbow_0 = '#e772df'
rainbow_1 = '#8895ff'
rainbow_2 = '#60bf88'
rainbow_3 = '#d37faf'
rainbow_4 = '#8fbaff'
rainbow_5 = '#a0c27f'
rainbow_6 = '#a698ef'
rainbow_7 = '#9ac2ff'
prose_todo = '#ff7560'
prose_done = '#60b444'
prose_tag = '#c9addf'
prose_table = '#afdacf'
err = '#ff7560'
warning = '#d4a052'
info = '#60b444'
hint = '#8ac0ef'
ok = '#60bf88'
