# Palette for Ef Tritanopia

[families.ef_tritanopia]
name = 'Ef Tritanopia'
license = 'GPL v3'
light_variant = 'ef_tritanopia_light'
dark_variant = 'ef_tritanopia_dark'

[variants.ef_tritanopia_light]
family = 'ef_tritanopia'
flavor = 'light'
foreground = '#1a1a1a'
background = '#fff9f9'
cursor = '#bb0000'
selection_background = '#dadadf'
selection_foreground = '#1a1a1a'
ansi = [
  '#fff9f9',
  '#aa0010',
  '#217a3c',
  '#805d00',
  '#375cd8',
  '#aa357f',
  '#2070af',
  '#1a1a1a',
  '#efecec',
  '#dd0000',
  '#4a7d00',
  '#965000',
  '#4250ef',
  '#bf256a',
  '#2f5faf',
  '#756275',
]

[variants.ef_tritanopia_light.extended]
none = 'NONE'
bg_main = '#fff9f9'
bg_dim = '#efecec'
bg_alt = '#ddd9d9'
fg_main = '#1a1a1a'
fg_dim = '#756275'
fg_alt = '#194f90'
border = '#adadad'
border_highlight = '#194f90'
red = '#aa0010'
red_warmer = '#dd0000'
red_cooler = '#c50f4f'
red_faint = '#92454f'
green = '#217a3c'
green_warmer = '#4a7d00'
green_cooler = '#008058'
green_faint = '#61756c'
yellow = '#805d00'
yellow_warmer = '#965000'
yellow_cooler = '#765040'
yellow_faint = '#776d6a'
blue = '#375cd8'
blue_warmer = '#4250ef'
blue_cooler = '#065fff'
blue_faint = '#6060d0'
magenta = '#aa357f'
magenta_warmer = '#bf256a'
magenta_cooler = '#af40af'
magenta_faint = '#7f4580'
cyan = '#2070af'
cyan_warmer = '#2f5faf'
cyan_cooler = '#007faa'
cyan_faint = '#5f6a90'
rust = '#dd0000'
gold = '#805d00'
olive = '#4a7d00'
slate = '#6060d0'
indigo = '#af40af'
maroon = '#c50f4f'
pink = '#bf256a'
red_intense = '#aa0010'
green_intense = '#217a3c'
yellow_intense = '#805d00'
blue_intense = '#375cd8'
magenta_intense = '#aa357f'
cyan_intense = '#2070af'
bg_red_intense = '#ffa2a0'
bg_green_intense = '#8aefef'
bg_yellow_intense = '#ff7f78'
bg_blue_intense = '#a8c8ef'
bg_magenta_intense = '#e09fc0'
bg_cyan_intense = '#7bcfcf'
bg_red_subtle = '#ffc4bf'
bg_green_subtle = '#baeecf'
bg_yellow_subtle = '#f5d8a8'
bg_blue_subtle = '#c8e6f7'
bg_magenta_subtle = '#ffcfe0'
bg_cyan_subtle = '#bbeff2'
bg_red_nuanced = '#ffc4bf'
bg_green_nuanced = '#baeecf'
bg_yellow_nuanced = '#f5d8a8'
bg_blue_nuanced = '#c8e6f7'
bg_magenta_nuanced = '#ffcfe0'
bg_cyan_nuanced = '#bbeff2'
bg_completion = '#ffcada'
bg_hl_line = '#ffdadf'
bg_paren_match = '#8fc0cf'
bg_paren_expression = '#8fcfff'
bg_char_0 = '#c8e6f7'
bg_char_1 = '#ffcfe0'
bg_char_2 = '#f5d8a8'
bg_active = '#bdb9b9'
fg_active = '#1a1a1a'
bg_inactive = '#f7f2f2'
fg_inactive = '#756275'
bg_status_line_active = '#ff99aa'
fg_status_line_active = '#1a0a0f'
bg_status_line_inactive = '#efecec'
fg_status_line_inactive = '#756275'
bg_tab_bar = '#ddd9d9'
bg_tab_current = '#fff9f9'
bg_tab_other = '#bdb9b9'
fg_tab_other = '#756275'
bg_tab_alternate = '#eda9dc'
bg_added = '#c9efea'
bg_added_faint = '#d7eff5'
bg_added_refine = '#b3dfdf'
bg_added_fringe = '#b3dfdf'
fg_added = '#004840'
fg_added_intense = '#004840'
bg_changed = '#dbdbff'
bg_changed_faint = '#e4e4ff'
bg_changed_refine = '#c0c0ef'
bg_changed_fringe = '#c0c0ef'
fg_changed = '#333399'
fg_changed_intense = '#333399'
bg_removed = '#ffd6e0'
bg_removed_faint = '#ffe9e6'
bg_removed_refine = '#f5bfc8'
bg_removed_fringe = '#f5bfc8'
fg_removed = '#8f1313'
fg_removed_intense = '#8f1313'
bg_diff_context = '#efecec'
visual = '#dadadf'
link = '#375cd8'
link_visited = '#af40af'
link_symbolic = '#2070af'
string = '#2070af'
comment = '#92454f'
constant = '#c50f4f'
identifier = '#7f4580'
keyword = '#aa0010'
type = '#2f5faf'
fnname = '#af40af'
variable = '#007faa'
rainbow_0 = '#2070af'
rainbow_1 = '#aa0010'
rainbow_2 = '#2f5faf'
rainbow_3 = '#c50f4f'
rainbow_4 = '#007faa'
rainbow_5 = '#aa357f'
rainbow_6 = '#5f6a90'
rainbow_7 = '#7f4580'
prose_todo = '#dd0000'
prose_done = '#2070af'
prose_tag = '#194f90'
prose_table = '#194f90'
err = '#dd0000'
warning = '#aa357f'
info = '#2070af'
hint = '#5f6a90'
ok = '#008058'

[variants.ef_tritanopia_dark]
family = 'ef_tritanopia'
flavor = 'dark'
foreground = '#dfd0d5'
background = '#15050f'
cursor = '#fd3333'
selection_background = '#293140'
selection_foreground = '#dfd0d5'
ansi = [
  '#15050f',
  '#cf4f5f',
  '#2fa526',
  '#c48702',
  '#379cf6',
  '#b0648f',
  '#3fafcf',
  '#dfd0d5',
  '#282026',
  '#df4f4f',
  '#64aa0f',
  '#d0730f',
  '#6a88ff',
  '#c560aa',
  '#3f9aaf',
  '#908890',
]

[variants.ef_tritanopia_dark.extended]
none = 'NONE'
bg_main = '#15050f'
bg_dim = '#282026'
bg_alt = '#352f2f'
fg_main = '#dfd0d5'
fg_dim = '#908890'
fg_alt = '#afdaef'
border = '#555564'
border_highlight = '#afdaef'
red = '#cf4f5f'
red_warmer = '#df4f4f'
red_cooler = '#d24f7f'
red_faint = '#b07f7f'
green = '#2fa526'
green_warmer = '#64aa0f'
green_cooler = '#00b066'
green_faint = '#5f9f6f'
yellow = '#c48702'
yellow_warmer = '#d0730f'
yellow_cooler = '#df8f6f'
yellow_faint = '#cf9f7f'
blue = '#379cf6'
blue_warmer = '#6a88ff'
blue_cooler = '#029fff'
blue_faint = '#6a84af'
magenta = '#b0648f'
magenta_warmer = '#c560aa'
magenta_cooler = '#a6699f'
magenta_faint = '#c590af'
cyan = '#3fafcf'
cyan_warmer = '#3f9aaf'
cyan_cooler = '#4fafaf'
cyan_faint = '#82a0af'
rust = '#df4f4f'
gold = '#c48702'
olive = '#64aa0f'
slate = '#6a84af'
indigo = '#a6699f'
maroon = '#d24f7f'
pink = '#c560aa'
red_intense = '#cf4f5f'
green_intense = '#2fa526'
yellow_intense = '#c48702'
blue_intense = '#379cf6'
magenta_intense = '#b0648f'
cyan_intense = '#3fafcf'
bg_red_intense = '#aa0010'
bg_green_intense = '#5f806f'
bg_yellow_intense = '#950f4f'
bg_blue_intense = '#165f70'
bg_magenta_intense = '#a04f9f'
bg_cyan_intense = '#007faa'
bg_red_subtle = '#6e1b20'
bg_green_subtle = '#054c38'
bg_yellow_subtle = '#65302f'
bg_blue_subtle = '#224360'
bg_magenta_subtle = '#603256'
bg_cyan_subtle = '#004a57'
bg_red_nuanced = '#6e1b20'
bg_green_nuanced = '#054c38'
bg_yellow_nuanced = '#65302f'
bg_blue_nuanced = '#224360'
bg_magenta_nuanced = '#603256'
bg_cyan_nuanced = '#004a57'
bg_completion = '#441824'
bg_hl_line = '#3f1515'
bg_paren_match = '#2f5f7a'
bg_paren_expression = '#00405f'
bg_char_0 = '#224360'
bg_char_1 = '#603256'
bg_char_2 = '#65302f'
bg_active = '#554f4f'
fg_active = '#dfd0d5'
bg_inactive = '#1a1517'
fg_inactive = '#908890'
bg_status_line_active = '#671822'
fg_status_line_active = '#ffffff'
bg_status_line_inactive = '#282026'
fg_status_line_inactive = '#908890'
bg_tab_bar = '#352f2f'
bg_tab_current = '#15050f'
bg_tab_other = '#554f4f'
fg_tab_other = '#908890'
bg_tab_alternate = '#5e3e5b'
bg_added = '#002d3f'
bg_added_faint = '#001f38'
bg_added_refine = '#003b4f'
bg_added_fringe = '#003b4f'
fg_added = '#cbdfff'
fg_added_intense = '#cbdfff'
bg_changed = '#352354'
bg_changed_faint = '#351444'
bg_changed_refine = '#383964'
bg_changed_fringe = '#383964'
fg_changed = '#e3cfff'
fg_changed_intense = '#e3cfff'
bg_removed = '#4d091f'
bg_removed_faint = '#37040f'
bg_removed_refine = '#6b0f26'
bg_removed_fringe = '#6b0f26'
fg_removed = '#ffbfbf'
fg_removed_intense = '#ffbfbf'
bg_diff_context = '#282026'
visual = '#293140'
link = '#379cf6'
link_visited = '#a6699f'
link_symbolic = '#3fafcf'
string = '#3fafcf'
comment = '#b07f7f'
constant = '#d24f7f'
identifier = '#c590af'
keyword = '#cf4f5f'
type = '#3f9aaf'
fnname = '#a6699f'
variable = '#4fafaf'
rainbow_0 = '#3fafcf'
rainbow_1 = '#cf4f5f'
rainbow_2 = '#3f9aaf'
rainbow_3 = '#d24f7f'
rainbow_4 = '#4fafaf'
rainbow_5 = '#b0648f'
rainbow_6 = '#82a0af'
rainbow_7 = '#c590af'
prose_todo = '#df4f4f'
prose_done = '#3fafcf'
prose_tag = '#afdaef'
prose_table = '#afdaef'
err = '#df4f4f'
warning = '#c560aa'
info = '#3fafcf'
hint = '#82a0af'
ok = '#00b066'
